{{- if .Values.metal3.enabled }}
{{- if not .Values.metal3.namespace }}
{{- fail "metal3.enabled is true but metal3.namespace is not set" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.inventoryConfig }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bare-metal-fulfillment-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  inventory.yaml: |
    name: metal3-inventory
    type: metal3
    hostClass: {{ .Values.metal3.hostClass }}
    networkClass: {{ .Values.metal3.networkClass }}
    options:
      metal3:
        namespace: {{ .Values.metal3.namespace }}
{{- end }}
