{{- if .Values.netbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.netboxToken }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bare-metal-fulfillment-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.netbox.token | quote }}
{{- if .Values.netbox.caCert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.netboxCA }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bare-metal-fulfillment-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.netbox.caCert | nindent 4 }}
{{- end }}
{{- end }}
