apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.1-nightly.20260909.89a42ed.77.1
appVersion: "0.0.1-nightly.20260909.89a42ed.77.1"
