apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.7-nightly.20261003.e5edbfb.117.1
appVersion: "0.0.7-nightly.20261003.e5edbfb.117.1"
