apiVersion: v2
name: osac-metering
description: OSAC Metering Service — collects metered events from OSAC tenant resource usage
type: application
version: 0.0.7-nightly.20260926.584cff1.110.1
appVersion: "0.0.7-nightly.20260926.584cff1.110.1"
