apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.configAsCode.secret }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
stringData:
  AAP_ADDON_OPERATOR_MAX_CONCURRENT_JOBS: {{ .Values.configAsCode.addonOperatorMaxConcurrentJobs | quote }}
  {{- $networking := ((.Values.global).networking) | default dict }}
  {{- $netris := $networking.netris | default dict }}
  {{- $caBundle := $netris.caBundle | default dict }}
  NETRIS_VALIDATE_CERTS: {{ $netris.validateCerts | default true | quote }}
  {{- with $caBundle.configMap }}
  NETRIS_CA_CONFIGMAP: {{ . | quote }}
  {{- end }}
  {{- if .Values.configAsCode.importAgentsEnabled }}
  OSAC_IMPORT_AGENTS_ENABLED: "true"
  {{- end }}
  {{- if .Values.configAsCode.importBcmAgentsEnabled }}
  OSAC_IMPORT_BCM_AGENTS_ENABLED: "true"
  {{- end }}
  {{- with .Values.configAsCode.eeImage }}
  AAP_EE_IMAGE: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.eeImagePull }}
  AAP_EE_IMAGE_PULL: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitUri }}
  AAP_PROJECT_GIT_URI: {{ . | quote }}
  {{- end }}
  {{- with .Values.configAsCode.projectGitBranch }}
  AAP_PROJECT_GIT_BRANCH: {{ . | quote }}
  {{- end }}
