---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccounts.templatePublisher }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-aap.labels" . | nindent 4 }}
