// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/auth (interfaces: JwksCache)
//
// Generated by this command:
//
//	mockgen -destination=auth_jwks_cache_mock.go -package=auth . JwksCache
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockJwksCache is a mock of JwksCache interface.
type MockJwksCache struct {
	ctrl     *gomock.Controller
	recorder *MockJwksCacheMockRecorder
	isgomock struct{}
}

// MockJwksCacheMockRecorder is the mock recorder for MockJwksCache.
type MockJwksCacheMockRecorder struct {
	mock *MockJwksCache
}

// NewMockJwksCache creates a new mock instance.
func NewMockJwksCache(ctrl *gomock.Controller) *MockJwksCache {
	mock := &MockJwksCache{ctrl: ctrl}
	mock.recorder = &MockJwksCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwksCache) EXPECT() *MockJwksCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockJwksCache) Get(ctx context.Context, issuerUrl, keyId string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, issuerUrl, keyId)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockJwksCacheMockRecorder) Get(ctx, issuerUrl, keyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockJwksCache)(nil).Get), ctx, issuerUrl, keyId)
}
