// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/auth (interfaces: AuthorizationEvaluator)
//
// Generated by this command:
//
//	mockgen -destination=internal/auth/authorization_evaluator_mock.go -package=auth github.com/osac-project/osac/fulfillment-service/internal/auth AuthorizationEvaluator
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizationEvaluator is a mock of AuthorizationEvaluator interface.
type MockAuthorizationEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizationEvaluatorMockRecorder
	isgomock struct{}
}

// MockAuthorizationEvaluatorMockRecorder is the mock recorder for MockAuthorizationEvaluator.
type MockAuthorizationEvaluatorMockRecorder struct {
	mock *MockAuthorizationEvaluator
}

// NewMockAuthorizationEvaluator creates a new mock instance.
func NewMockAuthorizationEvaluator(ctrl *gomock.Controller) *MockAuthorizationEvaluator {
	mock := &MockAuthorizationEvaluator{ctrl: ctrl}
	mock.recorder = &MockAuthorizationEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizationEvaluator) EXPECT() *MockAuthorizationEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockAuthorizationEvaluator) Evaluate(ctx context.Context, authContext *AuthContext, method string) (*AuthzDecision, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, authContext, method)
	ret0, _ := ret[0].(*AuthzDecision)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockAuthorizationEvaluatorMockRecorder) Evaluate(ctx, authContext, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockAuthorizationEvaluator)(nil).Evaluate), ctx, authContext, method)
}
