// Code generated by MockGen. DO NOT EDIT.
// Source: grpc_jit_provisioning_interceptor.go
//
// Generated by this command:
//
//	mockgen -source=grpc_jit_provisioning_interceptor.go -destination=grpc_jit_provisioning_interceptor_mock.go -package=auth UserProvisioner
//

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProvisioner is a mock of UserProvisioner interface.
type MockUserProvisioner struct {
	ctrl     *gomock.Controller
	recorder *MockUserProvisionerMockRecorder
	isgomock struct{}
}

// MockUserProvisionerMockRecorder is the mock recorder for MockUserProvisioner.
type MockUserProvisionerMockRecorder struct {
	mock *MockUserProvisioner
}

// NewMockUserProvisioner creates a new mock instance.
func NewMockUserProvisioner(ctrl *gomock.Controller) *MockUserProvisioner {
	mock := &MockUserProvisioner{ctrl: ctrl}
	mock.recorder = &MockUserProvisionerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProvisioner) EXPECT() *MockUserProvisionerMockRecorder {
	return m.recorder
}

// Provision mocks base method.
func (m *MockUserProvisioner) Provision(ctx context.Context, username, tenant string, claims jwt.MapClaims) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Provision", ctx, username, tenant, claims)
	ret0, _ := ret[0].(error)
	return ret0
}

// Provision indicates an expected call of Provision.
func (mr *MockUserProvisionerMockRecorder) Provision(ctx, username, tenant, claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Provision", reflect.TypeOf((*MockUserProvisioner)(nil).Provision), ctx, username, tenant, claims)
}
