repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-symlinks
    - id: detect-private-key

- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
    - id: yamllint
      files: \.(yaml|yml)$
      types: [file, yaml]
      entry: yamllint --strict
      exclude: ^(fulfillment-service/(charts|it/charts)/.*/templates/|osac-operator/(charts/.*/templates/|config/))

- repo: local
  hooks:
  - id: fulfillment-service-golangci-lint
    pass_filenames: false
    name: fulfillment-service golangci-lint
    language: system
    files: ^fulfillment-service/.*\.go$
    entry: bash -c "cd fulfillment-service && uv run dev.py lint go"
  - id: fulfillment-service-buf-lint
    pass_filenames: false
    name: fulfillment-service buf-lint
    language: system
    files: ^fulfillment-service/.*\.proto$
    entry: bash -c "cd fulfillment-service && uv run dev.py lint proto"
  - id: osac-operator-golangci-lint
    pass_filenames: false
    name: osac-operator golangci-lint
    language: system
    files: ^osac-operator/.*\.go$
    entry: bash -c "cd osac-operator && bin/golangci-lint run --fix"
