extends: default
ignore:
  - fulfillment-service/charts/*/templates/
  - fulfillment-service/it/charts/*/templates/
  - osac-operator/charts/*/templates/
  - osac-operator/config/
  - osac-aap/vendor/
  - osac-aap/charts/
  - bare-metal-fulfillment-operator/charts/*/templates/
  - bare-metal-fulfillment-operator/config/
  - osac-installer/charts/
  - osac-metering/charts/*/templates/
  - osac-csi-driver/charts/*/templates/
rules:
  line-length: disable
  document-start: disable
  indentation:
    indent-sequences: whatever
  hyphens:
    max-spaces-after: 4
  truthy:
    check-keys: false
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
