// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/health (interfaces: Reporter)
//
// Generated by this command:
//
//	mockgen -destination=health_reporter_mock.go -package=health . Reporter
//

// Package health is a generated GoMock package.
package health

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc_health_v1 "google.golang.org/grpc/health/grpc_health_v1"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Report mocks base method.
func (m *MockReporter) Report(ctx context.Context, name string, status grpc_health_v1.HealthCheckResponse_ServingStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Report", ctx, name, status)
}

// Report indicates an expected call of Report.
func (mr *MockReporterMockRecorder) Report(ctx, name, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Report", reflect.TypeOf((*MockReporter)(nil).Report), ctx, name, status)
}
