// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/tenants_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/tenants_service_grpc.pb.go -destination=tenants_client_mock.go -package=onboarding TenantsClient
//

// Package onboarding is a generated GoMock package.
package onboarding

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTenantsClient is a mock of TenantsClient interface.
type MockTenantsClient struct {
	ctrl     *gomock.Controller
	recorder *MockTenantsClientMockRecorder
	isgomock struct{}
}

// MockTenantsClientMockRecorder is the mock recorder for MockTenantsClient.
type MockTenantsClientMockRecorder struct {
	mock *MockTenantsClient
}

// NewMockTenantsClient creates a new mock instance.
func NewMockTenantsClient(ctrl *gomock.Controller) *MockTenantsClient {
	mock := &MockTenantsClient{ctrl: ctrl}
	mock.recorder = &MockTenantsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantsClient) EXPECT() *MockTenantsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantsClient) Create(ctx context.Context, in *privatev1.TenantsCreateRequest, opts ...grpc.CallOption) (*privatev1.TenantsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockTenantsClient) Delete(ctx context.Context, in *privatev1.TenantsDeleteRequest, opts ...grpc.CallOption) (*privatev1.TenantsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockTenantsClient) Get(ctx context.Context, in *privatev1.TenantsGetRequest, opts ...grpc.CallOption) (*privatev1.TenantsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockTenantsClient) List(ctx context.Context, in *privatev1.TenantsListRequest, opts ...grpc.CallOption) (*privatev1.TenantsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockTenantsClient) Signal(ctx context.Context, in *privatev1.TenantsSignalRequest, opts ...grpc.CallOption) (*privatev1.TenantsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockTenantsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockTenantsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockTenantsClient) Update(ctx context.Context, in *privatev1.TenantsUpdateRequest, opts ...grpc.CallOption) (*privatev1.TenantsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.TenantsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTenantsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantsClient)(nil).Update), varargs...)
}

// MockTenantsServer is a mock of TenantsServer interface.
type MockTenantsServer struct {
	ctrl     *gomock.Controller
	recorder *MockTenantsServerMockRecorder
	isgomock struct{}
}

// MockTenantsServerMockRecorder is the mock recorder for MockTenantsServer.
type MockTenantsServerMockRecorder struct {
	mock *MockTenantsServer
}

// NewMockTenantsServer creates a new mock instance.
func NewMockTenantsServer(ctrl *gomock.Controller) *MockTenantsServer {
	mock := &MockTenantsServer{ctrl: ctrl}
	mock.recorder = &MockTenantsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTenantsServer) EXPECT() *MockTenantsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTenantsServer) Create(arg0 context.Context, arg1 *privatev1.TenantsCreateRequest) (*privatev1.TenantsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTenantsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTenantsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockTenantsServer) Delete(arg0 context.Context, arg1 *privatev1.TenantsDeleteRequest) (*privatev1.TenantsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockTenantsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTenantsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockTenantsServer) Get(arg0 context.Context, arg1 *privatev1.TenantsGetRequest) (*privatev1.TenantsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTenantsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTenantsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockTenantsServer) List(arg0 context.Context, arg1 *privatev1.TenantsListRequest) (*privatev1.TenantsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTenantsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTenantsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockTenantsServer) Signal(arg0 context.Context, arg1 *privatev1.TenantsSignalRequest) (*privatev1.TenantsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockTenantsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockTenantsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockTenantsServer) Update(arg0 context.Context, arg1 *privatev1.TenantsUpdateRequest) (*privatev1.TenantsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.TenantsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTenantsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTenantsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedTenantsServer mocks base method.
func (m *MockTenantsServer) mustEmbedUnimplementedTenantsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTenantsServer")
}

// mustEmbedUnimplementedTenantsServer indicates an expected call of mustEmbedUnimplementedTenantsServer.
func (mr *MockTenantsServerMockRecorder) mustEmbedUnimplementedTenantsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTenantsServer", reflect.TypeOf((*MockTenantsServer)(nil).mustEmbedUnimplementedTenantsServer))
}

// MockUnsafeTenantsServer is a mock of UnsafeTenantsServer interface.
type MockUnsafeTenantsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeTenantsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeTenantsServerMockRecorder is the mock recorder for MockUnsafeTenantsServer.
type MockUnsafeTenantsServerMockRecorder struct {
	mock *MockUnsafeTenantsServer
}

// NewMockUnsafeTenantsServer creates a new mock instance.
func NewMockUnsafeTenantsServer(ctrl *gomock.Controller) *MockUnsafeTenantsServer {
	mock := &MockUnsafeTenantsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeTenantsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeTenantsServer) EXPECT() *MockUnsafeTenantsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedTenantsServer mocks base method.
func (m *MockUnsafeTenantsServer) mustEmbedUnimplementedTenantsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTenantsServer")
}

// mustEmbedUnimplementedTenantsServer indicates an expected call of mustEmbedUnimplementedTenantsServer.
func (mr *MockUnsafeTenantsServerMockRecorder) mustEmbedUnimplementedTenantsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTenantsServer", reflect.TypeOf((*MockUnsafeTenantsServer)(nil).mustEmbedUnimplementedTenantsServer))
}
