// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/external_ip_attachments_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/external_ip_attachments_service_grpc.pb.go -destination=external_ip_attachments_client_mock.go -package=externalipattachment ExternalIPAttachmentsClient
//

// Package externalipattachment is a generated GoMock package.
package externalipattachment

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockExternalIPAttachmentsClient is a mock of ExternalIPAttachmentsClient interface.
type MockExternalIPAttachmentsClient struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPAttachmentsClientMockRecorder
	isgomock struct{}
}

// MockExternalIPAttachmentsClientMockRecorder is the mock recorder for MockExternalIPAttachmentsClient.
type MockExternalIPAttachmentsClientMockRecorder struct {
	mock *MockExternalIPAttachmentsClient
}

// NewMockExternalIPAttachmentsClient creates a new mock instance.
func NewMockExternalIPAttachmentsClient(ctrl *gomock.Controller) *MockExternalIPAttachmentsClient {
	mock := &MockExternalIPAttachmentsClient{ctrl: ctrl}
	mock.recorder = &MockExternalIPAttachmentsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPAttachmentsClient) EXPECT() *MockExternalIPAttachmentsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPAttachmentsClient) Create(ctx context.Context, in *privatev1.ExternalIPAttachmentsCreateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPAttachmentsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockExternalIPAttachmentsClient) Delete(ctx context.Context, in *privatev1.ExternalIPAttachmentsDeleteRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPAttachmentsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockExternalIPAttachmentsClient) Get(ctx context.Context, in *privatev1.ExternalIPAttachmentsGetRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPAttachmentsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockExternalIPAttachmentsClient) List(ctx context.Context, in *privatev1.ExternalIPAttachmentsListRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPAttachmentsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockExternalIPAttachmentsClient) Signal(ctx context.Context, in *privatev1.ExternalIPAttachmentsSignalRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPAttachmentsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockExternalIPAttachmentsClient) Update(ctx context.Context, in *privatev1.ExternalIPAttachmentsUpdateRequest, opts ...grpc.CallOption) (*privatev1.ExternalIPAttachmentsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPAttachmentsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPAttachmentsClient)(nil).Update), varargs...)
}

// MockExternalIPAttachmentsServer is a mock of ExternalIPAttachmentsServer interface.
type MockExternalIPAttachmentsServer struct {
	ctrl     *gomock.Controller
	recorder *MockExternalIPAttachmentsServerMockRecorder
	isgomock struct{}
}

// MockExternalIPAttachmentsServerMockRecorder is the mock recorder for MockExternalIPAttachmentsServer.
type MockExternalIPAttachmentsServerMockRecorder struct {
	mock *MockExternalIPAttachmentsServer
}

// NewMockExternalIPAttachmentsServer creates a new mock instance.
func NewMockExternalIPAttachmentsServer(ctrl *gomock.Controller) *MockExternalIPAttachmentsServer {
	mock := &MockExternalIPAttachmentsServer{ctrl: ctrl}
	mock.recorder = &MockExternalIPAttachmentsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExternalIPAttachmentsServer) EXPECT() *MockExternalIPAttachmentsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockExternalIPAttachmentsServer) Create(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsCreateRequest) (*privatev1.ExternalIPAttachmentsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockExternalIPAttachmentsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockExternalIPAttachmentsServer) Delete(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsDeleteRequest) (*privatev1.ExternalIPAttachmentsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockExternalIPAttachmentsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockExternalIPAttachmentsServer) Get(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsGetRequest) (*privatev1.ExternalIPAttachmentsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockExternalIPAttachmentsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockExternalIPAttachmentsServer) List(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsListRequest) (*privatev1.ExternalIPAttachmentsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockExternalIPAttachmentsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockExternalIPAttachmentsServer) Signal(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsSignalRequest) (*privatev1.ExternalIPAttachmentsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockExternalIPAttachmentsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockExternalIPAttachmentsServer) Update(arg0 context.Context, arg1 *privatev1.ExternalIPAttachmentsUpdateRequest) (*privatev1.ExternalIPAttachmentsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ExternalIPAttachmentsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockExternalIPAttachmentsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedExternalIPAttachmentsServer mocks base method.
func (m *MockExternalIPAttachmentsServer) mustEmbedUnimplementedExternalIPAttachmentsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPAttachmentsServer")
}

// mustEmbedUnimplementedExternalIPAttachmentsServer indicates an expected call of mustEmbedUnimplementedExternalIPAttachmentsServer.
func (mr *MockExternalIPAttachmentsServerMockRecorder) mustEmbedUnimplementedExternalIPAttachmentsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPAttachmentsServer", reflect.TypeOf((*MockExternalIPAttachmentsServer)(nil).mustEmbedUnimplementedExternalIPAttachmentsServer))
}

// MockUnsafeExternalIPAttachmentsServer is a mock of UnsafeExternalIPAttachmentsServer interface.
type MockUnsafeExternalIPAttachmentsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeExternalIPAttachmentsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeExternalIPAttachmentsServerMockRecorder is the mock recorder for MockUnsafeExternalIPAttachmentsServer.
type MockUnsafeExternalIPAttachmentsServerMockRecorder struct {
	mock *MockUnsafeExternalIPAttachmentsServer
}

// NewMockUnsafeExternalIPAttachmentsServer creates a new mock instance.
func NewMockUnsafeExternalIPAttachmentsServer(ctrl *gomock.Controller) *MockUnsafeExternalIPAttachmentsServer {
	mock := &MockUnsafeExternalIPAttachmentsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeExternalIPAttachmentsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeExternalIPAttachmentsServer) EXPECT() *MockUnsafeExternalIPAttachmentsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedExternalIPAttachmentsServer mocks base method.
func (m *MockUnsafeExternalIPAttachmentsServer) mustEmbedUnimplementedExternalIPAttachmentsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedExternalIPAttachmentsServer")
}

// mustEmbedUnimplementedExternalIPAttachmentsServer indicates an expected call of mustEmbedUnimplementedExternalIPAttachmentsServer.
func (mr *MockUnsafeExternalIPAttachmentsServerMockRecorder) mustEmbedUnimplementedExternalIPAttachmentsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedExternalIPAttachmentsServer", reflect.TypeOf((*MockUnsafeExternalIPAttachmentsServer)(nil).mustEmbedUnimplementedExternalIPAttachmentsServer))
}
