FROM registry.access.redhat.com/ubi10/go-toolset:1.26 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /opt/app-root/src
COPY --chown=1001:0 go.mod go.sum ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -buildvcs=false -a -o echo-adapter ./cmd/echo-adapter

FROM registry.access.redhat.com/ubi10-minimal:10.2
WORKDIR /
COPY --from=builder /opt/app-root/src/echo-adapter .
USER 65532:65532
ENTRYPOINT ["/echo-adapter"]
