- name: Wait for DNS record {{ wait_for_dns_record }}
  ansible.builtin.command: >-
      dig {{ ('@' ~ wait_for_dns_server) if (wait_for_dns_server | default('') | length > 0) else '' }}
      +noall +answer {{ wait_for_dns_record }}
  register: wait_for_dns_info
  changed_when: false
  no_log: true
  until: (wait_for_dns_info.stdout | length > 0)
  retries: "{{ wait_for_dns_retries }}"
  delay: "{{ wait_for_dns_delay }}"
