// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/nat_gateways_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/nat_gateways_service_grpc.pb.go -destination=nat_gateways_client_mock.go -package=natgateway NATGatewaysClient
//

// Package natgateway is a generated GoMock package.
package natgateway

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockNATGatewaysClient is a mock of NATGatewaysClient interface.
type MockNATGatewaysClient struct {
	ctrl     *gomock.Controller
	recorder *MockNATGatewaysClientMockRecorder
	isgomock struct{}
}

// MockNATGatewaysClientMockRecorder is the mock recorder for MockNATGatewaysClient.
type MockNATGatewaysClientMockRecorder struct {
	mock *MockNATGatewaysClient
}

// NewMockNATGatewaysClient creates a new mock instance.
func NewMockNATGatewaysClient(ctrl *gomock.Controller) *MockNATGatewaysClient {
	mock := &MockNATGatewaysClient{ctrl: ctrl}
	mock.recorder = &MockNATGatewaysClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATGatewaysClient) EXPECT() *MockNATGatewaysClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNATGatewaysClient) Create(ctx context.Context, in *privatev1.NATGatewaysCreateRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNATGatewaysClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNATGatewaysClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockNATGatewaysClient) Delete(ctx context.Context, in *privatev1.NATGatewaysDeleteRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNATGatewaysClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNATGatewaysClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockNATGatewaysClient) Get(ctx context.Context, in *privatev1.NATGatewaysGetRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNATGatewaysClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNATGatewaysClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockNATGatewaysClient) List(ctx context.Context, in *privatev1.NATGatewaysListRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNATGatewaysClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNATGatewaysClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockNATGatewaysClient) Signal(ctx context.Context, in *privatev1.NATGatewaysSignalRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockNATGatewaysClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockNATGatewaysClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockNATGatewaysClient) Update(ctx context.Context, in *privatev1.NATGatewaysUpdateRequest, opts ...grpc.CallOption) (*privatev1.NATGatewaysUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.NATGatewaysUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNATGatewaysClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNATGatewaysClient)(nil).Update), varargs...)
}

// MockNATGatewaysServer is a mock of NATGatewaysServer interface.
type MockNATGatewaysServer struct {
	ctrl     *gomock.Controller
	recorder *MockNATGatewaysServerMockRecorder
	isgomock struct{}
}

// MockNATGatewaysServerMockRecorder is the mock recorder for MockNATGatewaysServer.
type MockNATGatewaysServerMockRecorder struct {
	mock *MockNATGatewaysServer
}

// NewMockNATGatewaysServer creates a new mock instance.
func NewMockNATGatewaysServer(ctrl *gomock.Controller) *MockNATGatewaysServer {
	mock := &MockNATGatewaysServer{ctrl: ctrl}
	mock.recorder = &MockNATGatewaysServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNATGatewaysServer) EXPECT() *MockNATGatewaysServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNATGatewaysServer) Create(arg0 context.Context, arg1 *privatev1.NATGatewaysCreateRequest) (*privatev1.NATGatewaysCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockNATGatewaysServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNATGatewaysServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockNATGatewaysServer) Delete(arg0 context.Context, arg1 *privatev1.NATGatewaysDeleteRequest) (*privatev1.NATGatewaysDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNATGatewaysServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNATGatewaysServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockNATGatewaysServer) Get(arg0 context.Context, arg1 *privatev1.NATGatewaysGetRequest) (*privatev1.NATGatewaysGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNATGatewaysServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNATGatewaysServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockNATGatewaysServer) List(arg0 context.Context, arg1 *privatev1.NATGatewaysListRequest) (*privatev1.NATGatewaysListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNATGatewaysServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNATGatewaysServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockNATGatewaysServer) Signal(arg0 context.Context, arg1 *privatev1.NATGatewaysSignalRequest) (*privatev1.NATGatewaysSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockNATGatewaysServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockNATGatewaysServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockNATGatewaysServer) Update(arg0 context.Context, arg1 *privatev1.NATGatewaysUpdateRequest) (*privatev1.NATGatewaysUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.NATGatewaysUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockNATGatewaysServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockNATGatewaysServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedNATGatewaysServer mocks base method.
func (m *MockNATGatewaysServer) mustEmbedUnimplementedNATGatewaysServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNATGatewaysServer")
}

// mustEmbedUnimplementedNATGatewaysServer indicates an expected call of mustEmbedUnimplementedNATGatewaysServer.
func (mr *MockNATGatewaysServerMockRecorder) mustEmbedUnimplementedNATGatewaysServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNATGatewaysServer", reflect.TypeOf((*MockNATGatewaysServer)(nil).mustEmbedUnimplementedNATGatewaysServer))
}

// MockUnsafeNATGatewaysServer is a mock of UnsafeNATGatewaysServer interface.
type MockUnsafeNATGatewaysServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeNATGatewaysServerMockRecorder
	isgomock struct{}
}

// MockUnsafeNATGatewaysServerMockRecorder is the mock recorder for MockUnsafeNATGatewaysServer.
type MockUnsafeNATGatewaysServerMockRecorder struct {
	mock *MockUnsafeNATGatewaysServer
}

// NewMockUnsafeNATGatewaysServer creates a new mock instance.
func NewMockUnsafeNATGatewaysServer(ctrl *gomock.Controller) *MockUnsafeNATGatewaysServer {
	mock := &MockUnsafeNATGatewaysServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeNATGatewaysServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeNATGatewaysServer) EXPECT() *MockUnsafeNATGatewaysServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedNATGatewaysServer mocks base method.
func (m *MockUnsafeNATGatewaysServer) mustEmbedUnimplementedNATGatewaysServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedNATGatewaysServer")
}

// mustEmbedUnimplementedNATGatewaysServer indicates an expected call of mustEmbedUnimplementedNATGatewaysServer.
func (mr *MockUnsafeNATGatewaysServerMockRecorder) mustEmbedUnimplementedNATGatewaysServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedNATGatewaysServer", reflect.TypeOf((*MockUnsafeNATGatewaysServer)(nil).mustEmbedUnimplementedNATGatewaysServer))
}
