FROM registry.access.redhat.com/ubi10/go-toolset:1.26.7-1788213683 AS builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /opt/app-root/src
COPY --chown=1001:0 schema/ schema/
COPY --chown=1001:0 metering-service/go.mod metering-service/go.sum metering-service/
RUN cd metering-service && go mod download

COPY --chown=1001:0 metering-service/ metering-service/

RUN cd metering-service && CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -buildvcs=false -a -o /opt/app-root/src/bin/metering-service ./cmd/metering-service

FROM registry.access.redhat.com/ubi10-minimal:10.2
WORKDIR /
COPY --from=builder /opt/app-root/src/bin/metering-service .
USER 65532:65532
ENTRYPOINT ["/metering-service"]
