// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/bare-metal-fulfillment-operator/internal/inventory (interfaces: BCMAPI,BMHLifecycleManager)
//
// Generated by this command:
//
//	mockgen -destination=bcm_mock_test.go -package=inventory . BCMAPI,BMHLifecycleManager
//

// Package inventory is a generated GoMock package.
package inventory

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	bcmclient "github.com/osac-project/osac/bare-metal-fulfillment-operator/internal/bcmclient"
	gomock "go.uber.org/mock/gomock"
	certwatcher "sigs.k8s.io/controller-runtime/pkg/certwatcher"
)

// MockBCMAPI is a mock of BCMAPI interface.
type MockBCMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBCMAPIMockRecorder
	isgomock struct{}
}

// MockBCMAPIMockRecorder is the mock recorder for MockBCMAPI.
type MockBCMAPIMockRecorder struct {
	mock *MockBCMAPI
}

// NewMockBCMAPI creates a new mock instance.
func NewMockBCMAPI(ctrl *gomock.Controller) *MockBCMAPI {
	mock := &MockBCMAPI{ctrl: ctrl}
	mock.recorder = &MockBCMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBCMAPI) EXPECT() *MockBCMAPIMockRecorder {
	return m.recorder
}

// CertWatcher mocks base method.
func (m *MockBCMAPI) CertWatcher() *certwatcher.CertWatcher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CertWatcher")
	ret0, _ := ret[0].(*certwatcher.CertWatcher)
	return ret0
}

// CertWatcher indicates an expected call of CertWatcher.
func (mr *MockBCMAPIMockRecorder) CertWatcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CertWatcher", reflect.TypeOf((*MockBCMAPI)(nil).CertWatcher))
}

// GetDevice mocks base method.
func (m *MockBCMAPI) GetDevice(ctx context.Context, hostname string) (*bcmclient.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, hostname)
	ret0, _ := ret[0].(*bcmclient.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockBCMAPIMockRecorder) GetDevice(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockBCMAPI)(nil).GetDevice), ctx, hostname)
}

// GetDevices mocks base method.
func (m *MockBCMAPI) GetDevices(ctx context.Context) ([]bcmclient.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].([]bcmclient.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockBCMAPIMockRecorder) GetDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockBCMAPI)(nil).GetDevices), ctx)
}

// UpdateDevice mocks base method.
func (m *MockBCMAPI) UpdateDevice(ctx context.Context, deviceRaw json.RawMessage) (*bcmclient.UpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, deviceRaw)
	ret0, _ := ret[0].(*bcmclient.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockBCMAPIMockRecorder) UpdateDevice(ctx, deviceRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockBCMAPI)(nil).UpdateDevice), ctx, deviceRaw)
}

// MockBMHLifecycleManager is a mock of BMHLifecycleManager interface.
type MockBMHLifecycleManager struct {
	ctrl     *gomock.Controller
	recorder *MockBMHLifecycleManagerMockRecorder
	isgomock struct{}
}

// MockBMHLifecycleManagerMockRecorder is the mock recorder for MockBMHLifecycleManager.
type MockBMHLifecycleManagerMockRecorder struct {
	mock *MockBMHLifecycleManager
}

// NewMockBMHLifecycleManager creates a new mock instance.
func NewMockBMHLifecycleManager(ctrl *gomock.Controller) *MockBMHLifecycleManager {
	mock := &MockBMHLifecycleManager{ctrl: ctrl}
	mock.recorder = &MockBMHLifecycleManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBMHLifecycleManager) EXPECT() *MockBMHLifecycleManagerMockRecorder {
	return m.recorder
}

// GetHardwareNICs mocks base method.
func (m *MockBMHLifecycleManager) GetHardwareNICs(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHardwareNICs", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHardwareNICs indicates an expected call of GetHardwareNICs.
func (mr *MockBMHLifecycleManagerMockRecorder) GetHardwareNICs(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHardwareNICs", reflect.TypeOf((*MockBMHLifecycleManager)(nil).GetHardwareNICs), ctx, name)
}

// IsBMHReady mocks base method.
func (m *MockBMHLifecycleManager) IsBMHReady(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBMHReady", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBMHReady indicates an expected call of IsBMHReady.
func (mr *MockBMHLifecycleManagerMockRecorder) IsBMHReady(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBMHReady", reflect.TypeOf((*MockBMHLifecycleManager)(nil).IsBMHReady), ctx, name)
}

// Namespace mocks base method.
func (m *MockBMHLifecycleManager) Namespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockBMHLifecycleManagerMockRecorder) Namespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockBMHLifecycleManager)(nil).Namespace))
}
