// Code generated by MockGen. DO NOT EDIT.
// Source: bcm.go
//
// Generated by this command:
//
//	mockgen -source=bcm.go -destination=bcm_mock_test.go -package=inventory BCMAPI,BMCDiscoverer
//

// Package inventory is a generated GoMock package.
package inventory

import (
	context "context"
	json "encoding/json"
	reflect "reflect"

	bcmclient "github.com/osac-project/osac/bare-metal-fulfillment-operator/internal/bcmclient"
	gomock "go.uber.org/mock/gomock"
	certwatcher "sigs.k8s.io/controller-runtime/pkg/certwatcher"
)

// MockBCMAPI is a mock of BCMAPI interface.
type MockBCMAPI struct {
	ctrl     *gomock.Controller
	recorder *MockBCMAPIMockRecorder
	isgomock struct{}
}

// MockBCMAPIMockRecorder is the mock recorder for MockBCMAPI.
type MockBCMAPIMockRecorder struct {
	mock *MockBCMAPI
}

// NewMockBCMAPI creates a new mock instance.
func NewMockBCMAPI(ctrl *gomock.Controller) *MockBCMAPI {
	mock := &MockBCMAPI{ctrl: ctrl}
	mock.recorder = &MockBCMAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBCMAPI) EXPECT() *MockBCMAPIMockRecorder {
	return m.recorder
}

// CertWatcher mocks base method.
func (m *MockBCMAPI) CertWatcher() *certwatcher.CertWatcher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CertWatcher")
	ret0, _ := ret[0].(*certwatcher.CertWatcher)
	return ret0
}

// CertWatcher indicates an expected call of CertWatcher.
func (mr *MockBCMAPIMockRecorder) CertWatcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CertWatcher", reflect.TypeOf((*MockBCMAPI)(nil).CertWatcher))
}

// GetCategories mocks base method.
func (m *MockBCMAPI) GetCategories(ctx context.Context) ([]bcmclient.Category, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCategories", ctx)
	ret0, _ := ret[0].([]bcmclient.Category)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCategories indicates an expected call of GetCategories.
func (mr *MockBCMAPIMockRecorder) GetCategories(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCategories", reflect.TypeOf((*MockBCMAPI)(nil).GetCategories), ctx)
}

// GetDevice mocks base method.
func (m *MockBCMAPI) GetDevice(ctx context.Context, hostname string) (*bcmclient.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, hostname)
	ret0, _ := ret[0].(*bcmclient.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockBCMAPIMockRecorder) GetDevice(ctx, hostname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockBCMAPI)(nil).GetDevice), ctx, hostname)
}

// GetDevices mocks base method.
func (m *MockBCMAPI) GetDevices(ctx context.Context) ([]bcmclient.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevices", ctx)
	ret0, _ := ret[0].([]bcmclient.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevices indicates an expected call of GetDevices.
func (mr *MockBCMAPIMockRecorder) GetDevices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevices", reflect.TypeOf((*MockBCMAPI)(nil).GetDevices), ctx)
}

// GetPartitions mocks base method.
func (m *MockBCMAPI) GetPartitions(ctx context.Context) ([]bcmclient.Partition, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPartitions", ctx)
	ret0, _ := ret[0].([]bcmclient.Partition)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPartitions indicates an expected call of GetPartitions.
func (mr *MockBCMAPIMockRecorder) GetPartitions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPartitions", reflect.TypeOf((*MockBCMAPI)(nil).GetPartitions), ctx)
}

// UpdateDevice mocks base method.
func (m *MockBCMAPI) UpdateDevice(ctx context.Context, deviceRaw json.RawMessage) (*bcmclient.UpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevice", ctx, deviceRaw)
	ret0, _ := ret[0].(*bcmclient.UpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDevice indicates an expected call of UpdateDevice.
func (mr *MockBCMAPIMockRecorder) UpdateDevice(ctx, deviceRaw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevice", reflect.TypeOf((*MockBCMAPI)(nil).UpdateDevice), ctx, deviceRaw)
}

// MockBMCDiscoverer is a mock of BMCDiscoverer interface.
type MockBMCDiscoverer struct {
	ctrl     *gomock.Controller
	recorder *MockBMCDiscovererMockRecorder
	isgomock struct{}
}

// MockBMCDiscovererMockRecorder is the mock recorder for MockBMCDiscoverer.
type MockBMCDiscovererMockRecorder struct {
	mock *MockBMCDiscoverer
}

// NewMockBMCDiscoverer creates a new mock instance.
func NewMockBMCDiscoverer(ctrl *gomock.Controller) *MockBMCDiscoverer {
	mock := &MockBMCDiscoverer{ctrl: ctrl}
	mock.recorder = &MockBMCDiscovererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBMCDiscoverer) EXPECT() *MockBMCDiscovererMockRecorder {
	return m.recorder
}

// DiscoverSystemPath mocks base method.
func (m *MockBMCDiscoverer) DiscoverSystemPath(ctx context.Context, bmcIP, bootMAC, username, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverSystemPath", ctx, bmcIP, bootMAC, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverSystemPath indicates an expected call of DiscoverSystemPath.
func (mr *MockBMCDiscovererMockRecorder) DiscoverSystemPath(ctx, bmcIP, bootMAC, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverSystemPath", reflect.TypeOf((*MockBMCDiscoverer)(nil).DiscoverSystemPath), ctx, bmcIP, bootMAC, username, password)
}
