// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/subnets_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/subnets_service_grpc.pb.go -destination=subnets_client_mock.go -package=subnet SubnetsClient
//

// Package subnet is a generated GoMock package.
package subnet

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockSubnetsClient is a mock of SubnetsClient interface.
type MockSubnetsClient struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetsClientMockRecorder
	isgomock struct{}
}

// MockSubnetsClientMockRecorder is the mock recorder for MockSubnetsClient.
type MockSubnetsClientMockRecorder struct {
	mock *MockSubnetsClient
}

// NewMockSubnetsClient creates a new mock instance.
func NewMockSubnetsClient(ctrl *gomock.Controller) *MockSubnetsClient {
	mock := &MockSubnetsClient{ctrl: ctrl}
	mock.recorder = &MockSubnetsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetsClient) EXPECT() *MockSubnetsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubnetsClient) Create(ctx context.Context, in *privatev1.SubnetsCreateRequest, opts ...grpc.CallOption) (*privatev1.SubnetsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubnetsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubnetsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockSubnetsClient) Delete(ctx context.Context, in *privatev1.SubnetsDeleteRequest, opts ...grpc.CallOption) (*privatev1.SubnetsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSubnetsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubnetsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockSubnetsClient) Get(ctx context.Context, in *privatev1.SubnetsGetRequest, opts ...grpc.CallOption) (*privatev1.SubnetsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubnetsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubnetsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockSubnetsClient) List(ctx context.Context, in *privatev1.SubnetsListRequest, opts ...grpc.CallOption) (*privatev1.SubnetsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubnetsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubnetsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockSubnetsClient) Signal(ctx context.Context, in *privatev1.SubnetsSignalRequest, opts ...grpc.CallOption) (*privatev1.SubnetsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockSubnetsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockSubnetsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockSubnetsClient) Update(ctx context.Context, in *privatev1.SubnetsUpdateRequest, opts ...grpc.CallOption) (*privatev1.SubnetsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.SubnetsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubnetsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubnetsClient)(nil).Update), varargs...)
}

// MockSubnetsServer is a mock of SubnetsServer interface.
type MockSubnetsServer struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetsServerMockRecorder
	isgomock struct{}
}

// MockSubnetsServerMockRecorder is the mock recorder for MockSubnetsServer.
type MockSubnetsServerMockRecorder struct {
	mock *MockSubnetsServer
}

// NewMockSubnetsServer creates a new mock instance.
func NewMockSubnetsServer(ctrl *gomock.Controller) *MockSubnetsServer {
	mock := &MockSubnetsServer{ctrl: ctrl}
	mock.recorder = &MockSubnetsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetsServer) EXPECT() *MockSubnetsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubnetsServer) Create(arg0 context.Context, arg1 *privatev1.SubnetsCreateRequest) (*privatev1.SubnetsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubnetsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubnetsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSubnetsServer) Delete(arg0 context.Context, arg1 *privatev1.SubnetsDeleteRequest) (*privatev1.SubnetsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockSubnetsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubnetsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockSubnetsServer) Get(arg0 context.Context, arg1 *privatev1.SubnetsGetRequest) (*privatev1.SubnetsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSubnetsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSubnetsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockSubnetsServer) List(arg0 context.Context, arg1 *privatev1.SubnetsListRequest) (*privatev1.SubnetsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubnetsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubnetsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockSubnetsServer) Signal(arg0 context.Context, arg1 *privatev1.SubnetsSignalRequest) (*privatev1.SubnetsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockSubnetsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockSubnetsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockSubnetsServer) Update(arg0 context.Context, arg1 *privatev1.SubnetsUpdateRequest) (*privatev1.SubnetsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.SubnetsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockSubnetsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubnetsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedSubnetsServer mocks base method.
func (m *MockSubnetsServer) mustEmbedUnimplementedSubnetsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSubnetsServer")
}

// mustEmbedUnimplementedSubnetsServer indicates an expected call of mustEmbedUnimplementedSubnetsServer.
func (mr *MockSubnetsServerMockRecorder) mustEmbedUnimplementedSubnetsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSubnetsServer", reflect.TypeOf((*MockSubnetsServer)(nil).mustEmbedUnimplementedSubnetsServer))
}

// MockUnsafeSubnetsServer is a mock of UnsafeSubnetsServer interface.
type MockUnsafeSubnetsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeSubnetsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeSubnetsServerMockRecorder is the mock recorder for MockUnsafeSubnetsServer.
type MockUnsafeSubnetsServerMockRecorder struct {
	mock *MockUnsafeSubnetsServer
}

// NewMockUnsafeSubnetsServer creates a new mock instance.
func NewMockUnsafeSubnetsServer(ctrl *gomock.Controller) *MockUnsafeSubnetsServer {
	mock := &MockUnsafeSubnetsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeSubnetsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeSubnetsServer) EXPECT() *MockUnsafeSubnetsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedSubnetsServer mocks base method.
func (m *MockUnsafeSubnetsServer) mustEmbedUnimplementedSubnetsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedSubnetsServer")
}

// mustEmbedUnimplementedSubnetsServer indicates an expected call of mustEmbedUnimplementedSubnetsServer.
func (mr *MockUnsafeSubnetsServerMockRecorder) mustEmbedUnimplementedSubnetsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedSubnetsServer", reflect.TypeOf((*MockUnsafeSubnetsServer)(nil).mustEmbedUnimplementedSubnetsServer))
}
