// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/proto/gen/osac/private/v1 (interfaces: EventsClient)
//
// Generated by this command:
//
//	mockgen -destination=events_client_mock.go -package=mocks github.com/osac-project/osac/proto/gen/osac/private/v1 EventsClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/proto/gen/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockEventsClient is a mock of EventsClient interface.
type MockEventsClient struct {
	ctrl     *gomock.Controller
	recorder *MockEventsClientMockRecorder
	isgomock struct{}
}

// MockEventsClientMockRecorder is the mock recorder for MockEventsClient.
type MockEventsClientMockRecorder struct {
	mock *MockEventsClient
}

// NewMockEventsClient creates a new mock instance.
func NewMockEventsClient(ctrl *gomock.Controller) *MockEventsClient {
	mock := &MockEventsClient{ctrl: ctrl}
	mock.recorder = &MockEventsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventsClient) EXPECT() *MockEventsClientMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockEventsClient) Watch(ctx context.Context, in *privatev1.EventsWatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[privatev1.EventsWatchResponse], error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Watch", varargs...)
	ret0, _ := ret[0].(grpc.ServerStreamingClient[privatev1.EventsWatchResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Watch indicates an expected call of Watch.
func (mr *MockEventsClientMockRecorder) Watch(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockEventsClient)(nil).Watch), varargs...)
}
