// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/servers (interfaces: HubClientProvider)
//
// Generated by this command:
//
//	mockgen -destination=hub_client_provider_mock.go -package=servers . HubClientProvider
//

// Package servers is a generated GoMock package.
package servers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHubClientProvider is a mock of HubClientProvider interface.
type MockHubClientProvider struct {
	ctrl     *gomock.Controller
	recorder *MockHubClientProviderMockRecorder
	isgomock struct{}
}

// MockHubClientProviderMockRecorder is the mock recorder for MockHubClientProvider.
type MockHubClientProviderMockRecorder struct {
	mock *MockHubClientProvider
}

// NewMockHubClientProvider creates a new mock instance.
func NewMockHubClientProvider(ctrl *gomock.Controller) *MockHubClientProvider {
	mock := &MockHubClientProvider{ctrl: ctrl}
	mock.recorder = &MockHubClientProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubClientProvider) EXPECT() *MockHubClientProviderMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockHubClientProvider) GetClient(ctx context.Context, hubID string) (*HubClientInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, hubID)
	ret0, _ := ret[0].(*HubClientInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockHubClientProviderMockRecorder) GetClient(ctx, hubID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockHubClientProvider)(nil).GetClient), ctx, hubID)
}
