// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/servers (interfaces: HubSecretFetcher)
//
// Generated by this command:
//
//	mockgen -destination=hub_secret_fetcher_mock.go -package=servers . HubSecretFetcher
//

// Package servers is a generated GoMock package.
package servers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHubSecretFetcher is a mock of HubSecretFetcher interface.
type MockHubSecretFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockHubSecretFetcherMockRecorder
	isgomock struct{}
}

// MockHubSecretFetcherMockRecorder is the mock recorder for MockHubSecretFetcher.
type MockHubSecretFetcherMockRecorder struct {
	mock *MockHubSecretFetcher
}

// NewMockHubSecretFetcher creates a new mock instance.
func NewMockHubSecretFetcher(ctrl *gomock.Controller) *MockHubSecretFetcher {
	mock := &MockHubSecretFetcher{ctrl: ctrl}
	mock.recorder = &MockHubSecretFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubSecretFetcher) EXPECT() *MockHubSecretFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockHubSecretFetcher) Fetch(ctx context.Context, coordinates map[string]string) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, coordinates)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockHubSecretFetcherMockRecorder) Fetch(ctx, coordinates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockHubSecretFetcher)(nil).Fetch), ctx, coordinates)
}
