// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/osac/private/v1/project_memberships_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/osac/private/v1/project_memberships_service_grpc.pb.go -destination=internal/controllers/projectmembership/project_memberships_client_mock.go -package=projectmembership ProjectMembershipsClient
//

// Package projectmembership is a generated GoMock package.
package projectmembership

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockProjectMembershipsClient is a mock of ProjectMembershipsClient interface.
type MockProjectMembershipsClient struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembershipsClientMockRecorder
	isgomock struct{}
}

// MockProjectMembershipsClientMockRecorder is the mock recorder for MockProjectMembershipsClient.
type MockProjectMembershipsClientMockRecorder struct {
	mock *MockProjectMembershipsClient
}

// NewMockProjectMembershipsClient creates a new mock instance.
func NewMockProjectMembershipsClient(ctrl *gomock.Controller) *MockProjectMembershipsClient {
	mock := &MockProjectMembershipsClient{ctrl: ctrl}
	mock.recorder = &MockProjectMembershipsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembershipsClient) EXPECT() *MockProjectMembershipsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectMembershipsClient) Create(ctx context.Context, in *privatev1.ProjectMembershipsCreateRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectMembershipsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectMembershipsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockProjectMembershipsClient) Delete(ctx context.Context, in *privatev1.ProjectMembershipsDeleteRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectMembershipsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectMembershipsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockProjectMembershipsClient) Get(ctx context.Context, in *privatev1.ProjectMembershipsGetRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectMembershipsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectMembershipsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockProjectMembershipsClient) List(ctx context.Context, in *privatev1.ProjectMembershipsListRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectMembershipsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectMembershipsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockProjectMembershipsClient) Signal(ctx context.Context, in *privatev1.ProjectMembershipsSignalRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockProjectMembershipsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockProjectMembershipsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockProjectMembershipsClient) Update(ctx context.Context, in *privatev1.ProjectMembershipsUpdateRequest, opts ...grpc.CallOption) (*privatev1.ProjectMembershipsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectMembershipsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectMembershipsClient)(nil).Update), varargs...)
}

// MockProjectMembershipsServer is a mock of ProjectMembershipsServer interface.
type MockProjectMembershipsServer struct {
	ctrl     *gomock.Controller
	recorder *MockProjectMembershipsServerMockRecorder
	isgomock struct{}
}

// MockProjectMembershipsServerMockRecorder is the mock recorder for MockProjectMembershipsServer.
type MockProjectMembershipsServerMockRecorder struct {
	mock *MockProjectMembershipsServer
}

// NewMockProjectMembershipsServer creates a new mock instance.
func NewMockProjectMembershipsServer(ctrl *gomock.Controller) *MockProjectMembershipsServer {
	mock := &MockProjectMembershipsServer{ctrl: ctrl}
	mock.recorder = &MockProjectMembershipsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProjectMembershipsServer) EXPECT() *MockProjectMembershipsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockProjectMembershipsServer) Create(arg0 context.Context, arg1 *privatev1.ProjectMembershipsCreateRequest) (*privatev1.ProjectMembershipsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockProjectMembershipsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockProjectMembershipsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockProjectMembershipsServer) Delete(arg0 context.Context, arg1 *privatev1.ProjectMembershipsDeleteRequest) (*privatev1.ProjectMembershipsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockProjectMembershipsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockProjectMembershipsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockProjectMembershipsServer) Get(arg0 context.Context, arg1 *privatev1.ProjectMembershipsGetRequest) (*privatev1.ProjectMembershipsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockProjectMembershipsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockProjectMembershipsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockProjectMembershipsServer) List(arg0 context.Context, arg1 *privatev1.ProjectMembershipsListRequest) (*privatev1.ProjectMembershipsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockProjectMembershipsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockProjectMembershipsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockProjectMembershipsServer) Signal(arg0 context.Context, arg1 *privatev1.ProjectMembershipsSignalRequest) (*privatev1.ProjectMembershipsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockProjectMembershipsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockProjectMembershipsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockProjectMembershipsServer) Update(arg0 context.Context, arg1 *privatev1.ProjectMembershipsUpdateRequest) (*privatev1.ProjectMembershipsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ProjectMembershipsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockProjectMembershipsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockProjectMembershipsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedProjectMembershipsServer mocks base method.
func (m *MockProjectMembershipsServer) mustEmbedUnimplementedProjectMembershipsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProjectMembershipsServer")
}

// mustEmbedUnimplementedProjectMembershipsServer indicates an expected call of mustEmbedUnimplementedProjectMembershipsServer.
func (mr *MockProjectMembershipsServerMockRecorder) mustEmbedUnimplementedProjectMembershipsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProjectMembershipsServer", reflect.TypeOf((*MockProjectMembershipsServer)(nil).mustEmbedUnimplementedProjectMembershipsServer))
}

// MockUnsafeProjectMembershipsServer is a mock of UnsafeProjectMembershipsServer interface.
type MockUnsafeProjectMembershipsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeProjectMembershipsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeProjectMembershipsServerMockRecorder is the mock recorder for MockUnsafeProjectMembershipsServer.
type MockUnsafeProjectMembershipsServerMockRecorder struct {
	mock *MockUnsafeProjectMembershipsServer
}

// NewMockUnsafeProjectMembershipsServer creates a new mock instance.
func NewMockUnsafeProjectMembershipsServer(ctrl *gomock.Controller) *MockUnsafeProjectMembershipsServer {
	mock := &MockUnsafeProjectMembershipsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeProjectMembershipsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeProjectMembershipsServer) EXPECT() *MockUnsafeProjectMembershipsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedProjectMembershipsServer mocks base method.
func (m *MockUnsafeProjectMembershipsServer) mustEmbedUnimplementedProjectMembershipsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedProjectMembershipsServer")
}

// mustEmbedUnimplementedProjectMembershipsServer indicates an expected call of mustEmbedUnimplementedProjectMembershipsServer.
func (mr *MockUnsafeProjectMembershipsServerMockRecorder) mustEmbedUnimplementedProjectMembershipsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedProjectMembershipsServer", reflect.TypeOf((*MockUnsafeProjectMembershipsServer)(nil).mustEmbedUnimplementedProjectMembershipsServer))
}
