// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/controllers (interfaces: HubCache)
//
// Generated by this command:
//
//	mockgen -destination=hub_cache_mock.go -package=controllers . HubCache
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHubCache is a mock of HubCache interface.
type MockHubCache struct {
	ctrl     *gomock.Controller
	recorder *MockHubCacheMockRecorder
	isgomock struct{}
}

// MockHubCacheMockRecorder is the mock recorder for MockHubCache.
type MockHubCacheMockRecorder struct {
	mock *MockHubCache
}

// NewMockHubCache creates a new mock instance.
func NewMockHubCache(ctrl *gomock.Controller) *MockHubCache {
	mock := &MockHubCache{ctrl: ctrl}
	mock.recorder = &MockHubCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubCache) EXPECT() *MockHubCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHubCache) Get(ctx context.Context, id string) (*HubEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*HubEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHubCacheMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHubCache)(nil).Get), ctx, id)
}
