// Code generated by MockGen. DO NOT EDIT.
// Source: ../api/osac/private/v1/hubs_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../api/osac/private/v1/hubs_service_grpc.pb.go -destination=hubs_client_mock.go -package=controllers HubsClient
//

// Package controllers is a generated GoMock package.
package controllers

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockHubsClient is a mock of HubsClient interface.
type MockHubsClient struct {
	ctrl     *gomock.Controller
	recorder *MockHubsClientMockRecorder
	isgomock struct{}
}

// MockHubsClientMockRecorder is the mock recorder for MockHubsClient.
type MockHubsClientMockRecorder struct {
	mock *MockHubsClient
}

// NewMockHubsClient creates a new mock instance.
func NewMockHubsClient(ctrl *gomock.Controller) *MockHubsClient {
	mock := &MockHubsClient{ctrl: ctrl}
	mock.recorder = &MockHubsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubsClient) EXPECT() *MockHubsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHubsClient) Create(ctx context.Context, in *privatev1.HubsCreateRequest, opts ...grpc.CallOption) (*privatev1.HubsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHubsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHubsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockHubsClient) Delete(ctx context.Context, in *privatev1.HubsDeleteRequest, opts ...grpc.CallOption) (*privatev1.HubsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHubsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHubsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockHubsClient) Get(ctx context.Context, in *privatev1.HubsGetRequest, opts ...grpc.CallOption) (*privatev1.HubsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHubsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHubsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockHubsClient) List(ctx context.Context, in *privatev1.HubsListRequest, opts ...grpc.CallOption) (*privatev1.HubsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHubsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHubsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockHubsClient) Signal(ctx context.Context, in *privatev1.HubsSignalRequest, opts ...grpc.CallOption) (*privatev1.HubsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockHubsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockHubsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockHubsClient) Update(ctx context.Context, in *privatev1.HubsUpdateRequest, opts ...grpc.CallOption) (*privatev1.HubsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.HubsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockHubsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHubsClient)(nil).Update), varargs...)
}

// MockHubsServer is a mock of HubsServer interface.
type MockHubsServer struct {
	ctrl     *gomock.Controller
	recorder *MockHubsServerMockRecorder
	isgomock struct{}
}

// MockHubsServerMockRecorder is the mock recorder for MockHubsServer.
type MockHubsServerMockRecorder struct {
	mock *MockHubsServer
}

// NewMockHubsServer creates a new mock instance.
func NewMockHubsServer(ctrl *gomock.Controller) *MockHubsServer {
	mock := &MockHubsServer{ctrl: ctrl}
	mock.recorder = &MockHubsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHubsServer) EXPECT() *MockHubsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockHubsServer) Create(arg0 context.Context, arg1 *privatev1.HubsCreateRequest) (*privatev1.HubsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockHubsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockHubsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockHubsServer) Delete(arg0 context.Context, arg1 *privatev1.HubsDeleteRequest) (*privatev1.HubsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockHubsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockHubsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockHubsServer) Get(arg0 context.Context, arg1 *privatev1.HubsGetRequest) (*privatev1.HubsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHubsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHubsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockHubsServer) List(arg0 context.Context, arg1 *privatev1.HubsListRequest) (*privatev1.HubsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockHubsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockHubsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockHubsServer) Signal(arg0 context.Context, arg1 *privatev1.HubsSignalRequest) (*privatev1.HubsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockHubsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockHubsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockHubsServer) Update(arg0 context.Context, arg1 *privatev1.HubsUpdateRequest) (*privatev1.HubsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.HubsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockHubsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockHubsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedHubsServer mocks base method.
func (m *MockHubsServer) mustEmbedUnimplementedHubsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedHubsServer")
}

// mustEmbedUnimplementedHubsServer indicates an expected call of mustEmbedUnimplementedHubsServer.
func (mr *MockHubsServerMockRecorder) mustEmbedUnimplementedHubsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedHubsServer", reflect.TypeOf((*MockHubsServer)(nil).mustEmbedUnimplementedHubsServer))
}

// MockUnsafeHubsServer is a mock of UnsafeHubsServer interface.
type MockUnsafeHubsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeHubsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeHubsServerMockRecorder is the mock recorder for MockUnsafeHubsServer.
type MockUnsafeHubsServerMockRecorder struct {
	mock *MockUnsafeHubsServer
}

// NewMockUnsafeHubsServer creates a new mock instance.
func NewMockUnsafeHubsServer(ctrl *gomock.Controller) *MockUnsafeHubsServer {
	mock := &MockUnsafeHubsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeHubsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeHubsServer) EXPECT() *MockUnsafeHubsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedHubsServer mocks base method.
func (m *MockUnsafeHubsServer) mustEmbedUnimplementedHubsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedHubsServer")
}

// mustEmbedUnimplementedHubsServer indicates an expected call of mustEmbedUnimplementedHubsServer.
func (mr *MockUnsafeHubsServerMockRecorder) mustEmbedUnimplementedHubsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedHubsServer", reflect.TypeOf((*MockUnsafeHubsServer)(nil).mustEmbedUnimplementedHubsServer))
}
