// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/compute_instances_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/compute_instances_service_grpc.pb.go -destination=compute_instances_client_mock.go -package=computeinstance ComputeInstancesClient
//

// Package computeinstance is a generated GoMock package.
package computeinstance

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockComputeInstancesClient is a mock of ComputeInstancesClient interface.
type MockComputeInstancesClient struct {
	ctrl     *gomock.Controller
	recorder *MockComputeInstancesClientMockRecorder
	isgomock struct{}
}

// MockComputeInstancesClientMockRecorder is the mock recorder for MockComputeInstancesClient.
type MockComputeInstancesClientMockRecorder struct {
	mock *MockComputeInstancesClient
}

// NewMockComputeInstancesClient creates a new mock instance.
func NewMockComputeInstancesClient(ctrl *gomock.Controller) *MockComputeInstancesClient {
	mock := &MockComputeInstancesClient{ctrl: ctrl}
	mock.recorder = &MockComputeInstancesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputeInstancesClient) EXPECT() *MockComputeInstancesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComputeInstancesClient) Create(ctx context.Context, in *privatev1.ComputeInstancesCreateRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockComputeInstancesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComputeInstancesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockComputeInstancesClient) Delete(ctx context.Context, in *privatev1.ComputeInstancesDeleteRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockComputeInstancesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockComputeInstancesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockComputeInstancesClient) Get(ctx context.Context, in *privatev1.ComputeInstancesGetRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComputeInstancesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComputeInstancesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockComputeInstancesClient) List(ctx context.Context, in *privatev1.ComputeInstancesListRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockComputeInstancesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockComputeInstancesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockComputeInstancesClient) Signal(ctx context.Context, in *privatev1.ComputeInstancesSignalRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockComputeInstancesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockComputeInstancesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockComputeInstancesClient) Update(ctx context.Context, in *privatev1.ComputeInstancesUpdateRequest, opts ...grpc.CallOption) (*privatev1.ComputeInstancesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockComputeInstancesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComputeInstancesClient)(nil).Update), varargs...)
}

// MockComputeInstancesServer is a mock of ComputeInstancesServer interface.
type MockComputeInstancesServer struct {
	ctrl     *gomock.Controller
	recorder *MockComputeInstancesServerMockRecorder
	isgomock struct{}
}

// MockComputeInstancesServerMockRecorder is the mock recorder for MockComputeInstancesServer.
type MockComputeInstancesServerMockRecorder struct {
	mock *MockComputeInstancesServer
}

// NewMockComputeInstancesServer creates a new mock instance.
func NewMockComputeInstancesServer(ctrl *gomock.Controller) *MockComputeInstancesServer {
	mock := &MockComputeInstancesServer{ctrl: ctrl}
	mock.recorder = &MockComputeInstancesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComputeInstancesServer) EXPECT() *MockComputeInstancesServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockComputeInstancesServer) Create(arg0 context.Context, arg1 *privatev1.ComputeInstancesCreateRequest) (*privatev1.ComputeInstancesCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockComputeInstancesServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockComputeInstancesServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockComputeInstancesServer) Delete(arg0 context.Context, arg1 *privatev1.ComputeInstancesDeleteRequest) (*privatev1.ComputeInstancesDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockComputeInstancesServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockComputeInstancesServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockComputeInstancesServer) Get(arg0 context.Context, arg1 *privatev1.ComputeInstancesGetRequest) (*privatev1.ComputeInstancesGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockComputeInstancesServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockComputeInstancesServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockComputeInstancesServer) List(arg0 context.Context, arg1 *privatev1.ComputeInstancesListRequest) (*privatev1.ComputeInstancesListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockComputeInstancesServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockComputeInstancesServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockComputeInstancesServer) Signal(arg0 context.Context, arg1 *privatev1.ComputeInstancesSignalRequest) (*privatev1.ComputeInstancesSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockComputeInstancesServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockComputeInstancesServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockComputeInstancesServer) Update(arg0 context.Context, arg1 *privatev1.ComputeInstancesUpdateRequest) (*privatev1.ComputeInstancesUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ComputeInstancesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockComputeInstancesServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockComputeInstancesServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedComputeInstancesServer mocks base method.
func (m *MockComputeInstancesServer) mustEmbedUnimplementedComputeInstancesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedComputeInstancesServer")
}

// mustEmbedUnimplementedComputeInstancesServer indicates an expected call of mustEmbedUnimplementedComputeInstancesServer.
func (mr *MockComputeInstancesServerMockRecorder) mustEmbedUnimplementedComputeInstancesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedComputeInstancesServer", reflect.TypeOf((*MockComputeInstancesServer)(nil).mustEmbedUnimplementedComputeInstancesServer))
}

// MockUnsafeComputeInstancesServer is a mock of UnsafeComputeInstancesServer interface.
type MockUnsafeComputeInstancesServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeComputeInstancesServerMockRecorder
	isgomock struct{}
}

// MockUnsafeComputeInstancesServerMockRecorder is the mock recorder for MockUnsafeComputeInstancesServer.
type MockUnsafeComputeInstancesServerMockRecorder struct {
	mock *MockUnsafeComputeInstancesServer
}

// NewMockUnsafeComputeInstancesServer creates a new mock instance.
func NewMockUnsafeComputeInstancesServer(ctrl *gomock.Controller) *MockUnsafeComputeInstancesServer {
	mock := &MockUnsafeComputeInstancesServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeComputeInstancesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeComputeInstancesServer) EXPECT() *MockUnsafeComputeInstancesServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedComputeInstancesServer mocks base method.
func (m *MockUnsafeComputeInstancesServer) mustEmbedUnimplementedComputeInstancesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedComputeInstancesServer")
}

// mustEmbedUnimplementedComputeInstancesServer indicates an expected call of mustEmbedUnimplementedComputeInstancesServer.
func (mr *MockUnsafeComputeInstancesServerMockRecorder) mustEmbedUnimplementedComputeInstancesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedComputeInstancesServer", reflect.TypeOf((*MockUnsafeComputeInstancesServer)(nil).mustEmbedUnimplementedComputeInstancesServer))
}
