// Code generated by MockGen. DO NOT EDIT.
// Source: internal/api/osac/private/v1/disk_images_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/api/osac/private/v1/disk_images_service_grpc.pb.go -destination=internal/controllers/computeinstance/disk_images_client_mock.go -package=computeinstance DiskImagesClient
//

// Package computeinstance is a generated GoMock package.
package computeinstance

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockDiskImagesClient is a mock of DiskImagesClient interface.
type MockDiskImagesClient struct {
	ctrl     *gomock.Controller
	recorder *MockDiskImagesClientMockRecorder
	isgomock struct{}
}

// MockDiskImagesClientMockRecorder is the mock recorder for MockDiskImagesClient.
type MockDiskImagesClientMockRecorder struct {
	mock *MockDiskImagesClient
}

// NewMockDiskImagesClient creates a new mock instance.
func NewMockDiskImagesClient(ctrl *gomock.Controller) *MockDiskImagesClient {
	mock := &MockDiskImagesClient{ctrl: ctrl}
	mock.recorder = &MockDiskImagesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskImagesClient) EXPECT() *MockDiskImagesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiskImagesClient) Create(ctx context.Context, in *privatev1.DiskImagesCreateRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiskImagesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiskImagesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockDiskImagesClient) Delete(ctx context.Context, in *privatev1.DiskImagesDeleteRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDiskImagesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiskImagesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockDiskImagesClient) Get(ctx context.Context, in *privatev1.DiskImagesGetRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiskImagesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiskImagesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockDiskImagesClient) List(ctx context.Context, in *privatev1.DiskImagesListRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDiskImagesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiskImagesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockDiskImagesClient) Signal(ctx context.Context, in *privatev1.DiskImagesSignalRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockDiskImagesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockDiskImagesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockDiskImagesClient) Update(ctx context.Context, in *privatev1.DiskImagesUpdateRequest, opts ...grpc.CallOption) (*privatev1.DiskImagesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.DiskImagesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDiskImagesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiskImagesClient)(nil).Update), varargs...)
}

// MockDiskImagesServer is a mock of DiskImagesServer interface.
type MockDiskImagesServer struct {
	ctrl     *gomock.Controller
	recorder *MockDiskImagesServerMockRecorder
	isgomock struct{}
}

// MockDiskImagesServerMockRecorder is the mock recorder for MockDiskImagesServer.
type MockDiskImagesServerMockRecorder struct {
	mock *MockDiskImagesServer
}

// NewMockDiskImagesServer creates a new mock instance.
func NewMockDiskImagesServer(ctrl *gomock.Controller) *MockDiskImagesServer {
	mock := &MockDiskImagesServer{ctrl: ctrl}
	mock.recorder = &MockDiskImagesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiskImagesServer) EXPECT() *MockDiskImagesServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDiskImagesServer) Create(arg0 context.Context, arg1 *privatev1.DiskImagesCreateRequest) (*privatev1.DiskImagesCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDiskImagesServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDiskImagesServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockDiskImagesServer) Delete(arg0 context.Context, arg1 *privatev1.DiskImagesDeleteRequest) (*privatev1.DiskImagesDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDiskImagesServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDiskImagesServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockDiskImagesServer) Get(arg0 context.Context, arg1 *privatev1.DiskImagesGetRequest) (*privatev1.DiskImagesGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDiskImagesServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDiskImagesServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockDiskImagesServer) List(arg0 context.Context, arg1 *privatev1.DiskImagesListRequest) (*privatev1.DiskImagesListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDiskImagesServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDiskImagesServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockDiskImagesServer) Signal(arg0 context.Context, arg1 *privatev1.DiskImagesSignalRequest) (*privatev1.DiskImagesSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockDiskImagesServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockDiskImagesServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockDiskImagesServer) Update(arg0 context.Context, arg1 *privatev1.DiskImagesUpdateRequest) (*privatev1.DiskImagesUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.DiskImagesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDiskImagesServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDiskImagesServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedDiskImagesServer mocks base method.
func (m *MockDiskImagesServer) mustEmbedUnimplementedDiskImagesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedDiskImagesServer")
}

// mustEmbedUnimplementedDiskImagesServer indicates an expected call of mustEmbedUnimplementedDiskImagesServer.
func (mr *MockDiskImagesServerMockRecorder) mustEmbedUnimplementedDiskImagesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedDiskImagesServer", reflect.TypeOf((*MockDiskImagesServer)(nil).mustEmbedUnimplementedDiskImagesServer))
}

// MockUnsafeDiskImagesServer is a mock of UnsafeDiskImagesServer interface.
type MockUnsafeDiskImagesServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeDiskImagesServerMockRecorder
	isgomock struct{}
}

// MockUnsafeDiskImagesServerMockRecorder is the mock recorder for MockUnsafeDiskImagesServer.
type MockUnsafeDiskImagesServerMockRecorder struct {
	mock *MockUnsafeDiskImagesServer
}

// NewMockUnsafeDiskImagesServer creates a new mock instance.
func NewMockUnsafeDiskImagesServer(ctrl *gomock.Controller) *MockUnsafeDiskImagesServer {
	mock := &MockUnsafeDiskImagesServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeDiskImagesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeDiskImagesServer) EXPECT() *MockUnsafeDiskImagesServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedDiskImagesServer mocks base method.
func (m *MockUnsafeDiskImagesServer) mustEmbedUnimplementedDiskImagesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedDiskImagesServer")
}

// mustEmbedUnimplementedDiskImagesServer indicates an expected call of mustEmbedUnimplementedDiskImagesServer.
func (mr *MockUnsafeDiskImagesServerMockRecorder) mustEmbedUnimplementedDiskImagesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedDiskImagesServer", reflect.TypeOf((*MockUnsafeDiskImagesServer)(nil).mustEmbedUnimplementedDiskImagesServer))
}
