apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osac-metering.fullname" . }}
  labels:
    {{- include "osac-metering.labels" . | nindent 4 }}
    app.kubernetes.io/component: metering
