// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/fulfillment-service/internal/vault (interfaces: LifecycleClient)
//
// Generated by this command:
//
//	mockgen -destination=vault_lifecycle_mock.go -package=vault . LifecycleClient
//

// Package vault is a generated GoMock package.
package vault

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLifecycleClient is a mock of LifecycleClient interface.
type MockLifecycleClient struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleClientMockRecorder
	isgomock struct{}
}

// MockLifecycleClientMockRecorder is the mock recorder for MockLifecycleClient.
type MockLifecycleClientMockRecorder struct {
	mock *MockLifecycleClient
}

// NewMockLifecycleClient creates a new mock instance.
func NewMockLifecycleClient(ctrl *gomock.Controller) *MockLifecycleClient {
	mock := &MockLifecycleClient{ctrl: ctrl}
	mock.recorder = &MockLifecycleClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycleClient) EXPECT() *MockLifecycleClientMockRecorder {
	return m.recorder
}

// DeleteTenantNamespace mocks base method.
func (m *MockLifecycleClient) DeleteTenantNamespace(ctx context.Context, tenantName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTenantNamespace", ctx, tenantName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTenantNamespace indicates an expected call of DeleteTenantNamespace.
func (mr *MockLifecycleClientMockRecorder) DeleteTenantNamespace(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTenantNamespace", reflect.TypeOf((*MockLifecycleClient)(nil).DeleteTenantNamespace), ctx, tenantName)
}

// EnsureTenantNamespace mocks base method.
func (m *MockLifecycleClient) EnsureTenantNamespace(ctx context.Context, tenantName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureTenantNamespace", ctx, tenantName)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureTenantNamespace indicates an expected call of EnsureTenantNamespace.
func (mr *MockLifecycleClientMockRecorder) EnsureTenantNamespace(ctx, tenantName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureTenantNamespace", reflect.TypeOf((*MockLifecycleClient)(nil).EnsureTenantNamespace), ctx, tenantName)
}
