apiVersion: v2
name: csi-backends
description: Vendor CSI controller deployments for the OSAC CSI meta-driver
type: application
version: 0.0.8-nightly.20261006.c8d0d88.120.1
appVersion: 0.0.8-nightly.20261006.c8d0d88.120.1
