apiVersion: v2
name: csi-backends
description: Vendor CSI controller deployments for the OSAC CSI meta-driver
type: application
version: 0.0.11-nightly.20261009.f083108.123.1
appVersion: 0.0.11-nightly.20261009.f083108.123.1
