namespace: osac-csi-backends

imagePullSecrets: []

trident:
  enabled: false
  image:
    repository: registry.connect.redhat.com/netapp/trident
    tag: 25.10.0
  service:
    port: 50051
  config:
    certsSecret: ""

vast:
  enabled: false
  image:
    repository: docker.io/vastdataorg/csi
    tag: v2.6.5
  service:
    port: 50051
  config:
    vmsHost: ""
    vipPoolName: ""
    nfsExport: /k8s
    viewPolicy: default
    verifySsl: "true"
    credentialsSecret: ""

pure:
  enabled: false
  image:
    repository: docker.io/portworx/px-pure-csi-driver
    tag: "26.2.0"
  service:
    port: 50051
  config:
    credentialsSecret: ""
    clusterUuid: ""
    nodePluginNamespace: ""
