//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/baremetal_instance_catalog_item_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb";
import type { BareMetalInstanceRunStrategyFieldPolicy, BareMetalInstanceTypeLocalReferenceFieldPolicy, BareMetalNetworkAttachmentListFieldPolicy, BoolFieldPolicy, DiskImageReferenceFieldPolicy, StringFieldPolicy, TemplateParameterPolicy } from "./field_policy_type_pb";
import { file_osac_private_v1_field_policy_type } from "./field_policy_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { BareMetalInstanceTemplateReference } from "./baremetal_instance_template_type_pb";
import { file_osac_private_v1_baremetal_instance_template_type } from "./baremetal_instance_template_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/baremetal_instance_catalog_item_type.proto.
 */
export const file_osac_private_v1_baremetal_instance_catalog_item_type: GenFile = /*@__PURE__*/
  fileDesc("Cjpvc2FjL3ByaXZhdGUvdjEvYmFyZW1ldGFsX2luc3RhbmNlX2NhdGFsb2dfaXRlbV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEimAQKHEJhcmVNZXRhbEluc3RhbmNlQ2F0YWxvZ0l0ZW0SCgoCaWQYASABKAkSKwoIbWV0YWRhdGEYAiABKAsyGS5vc2FjLnByaXZhdGUudjEuTWV0YWRhdGESDQoFdGl0bGUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSUwoIdGVtcGxhdGUYBSABKAsyMy5vc2FjLnByaXZhdGUudjEuQmFyZU1ldGFsSW5zdGFuY2VUZW1wbGF0ZVJlZmVyZW5jZUIM4EEC4EEFukgDyAEBEhEKCXB1Ymxpc2hlZBgGIAEoCBJiChN0ZW1wbGF0ZV9wYXJhbWV0ZXJzGAkgAygLMkUub3NhYy5wcml2YXRlLnYxLkJhcmVNZXRhbEluc3RhbmNlQ2F0YWxvZ0l0ZW0uVGVtcGxhdGVQYXJhbWV0ZXJzRW50cnkSQwoGZmllbGRzGAogASgLMjMub3NhYy5wcml2YXRlLnYxLkJhcmVNZXRhbEluc3RhbmNlQ2F0YWxvZ0l0ZW1GaWVsZHMaYwoXVGVtcGxhdGVQYXJhbWV0ZXJzRW50cnkSCwoDa2V5GAEgASgJEjcKBXZhbHVlGAIgASgLMigub3NhYy5wcml2YXRlLnYxLlRlbXBsYXRlUGFyYW1ldGVyUG9saWN5OgI4AUoECAcQCEoECAgQCVIGdGVuYW50UhFmaWVsZF9kZWZpbml0aW9ucyKwBAoiQmFyZU1ldGFsSW5zdGFuY2VDYXRhbG9nSXRlbUZpZWxkcxI6Cg5zc2hfcHVibGljX2tleRgBIAEoCzIiLm9zYWMucHJpdmF0ZS52MS5TdHJpbmdGaWVsZFBvbGljeRI1Cgl1c2VyX2RhdGEYAiABKAsyIi5vc2FjLnByaXZhdGUudjEuU3RyaW5nRmllbGRQb2xpY3kSTgoMcnVuX3N0cmF0ZWd5GAMgASgLMjgub3NhYy5wcml2YXRlLnYxLkJhcmVNZXRhbEluc3RhbmNlUnVuU3RyYXRlZ3lGaWVsZFBvbGljeRJXChNuZXR3b3JrX2F0dGFjaG1lbnRzGAUgASgLMjoub3NhYy5wcml2YXRlLnYxLkJhcmVNZXRhbE5ldHdvcmtBdHRhY2htZW50TGlzdEZpZWxkUG9saWN5EkUKG2F1dG9fZXh0ZXJuYWxfaXBfYXR0YWNobWVudBgGIAEoCzIgLm9zYWMucHJpdmF0ZS52MS5Cb29sRmllbGRQb2xpY3kSVgoNaW5zdGFuY2VfdHlwZRgHIAEoCzI/Lm9zYWMucHJpdmF0ZS52MS5CYXJlTWV0YWxJbnN0YW5jZVR5cGVMb2NhbFJlZmVyZW5jZUZpZWxkUG9saWN5EkIKCmRpc2tfaW1hZ2UYCCABKAsyLi5vc2FjLnByaXZhdGUudjEuRGlza0ltYWdlUmVmZXJlbmNlRmllbGRQb2xpY3lKBAgEEAVSBWltYWdlImIKJUJhcmVNZXRhbEluc3RhbmNlQ2F0YWxvZ0l0ZW1SZWZlcmVuY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCRIPCgdwcm9qZWN0GAMgASgJEg4KBnNoYXJlZBgEIAEoCEIUirUYEBIOb3NhYy5wdWJsaWMudjFiBnByb3RvMw", [file_buf_validate_validate, file_cleanapi_cleanapi, file_google_api_field_behavior, file_osac_private_v1_field_policy_type, file_osac_private_v1_metadata_type, file_osac_private_v1_baremetal_instance_template_type]);

/**
 * A bare metal instance catalog item defines a curated hardware offering that references an underlying bare metal
 * instance template. Admins control typed resource-field and template-parameter policies, including locked values and defaults.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.BareMetalInstanceCatalogItem
 */
export type BareMetalInstanceCatalogItem = Message<"osac.private.v1.BareMetalInstanceCatalogItem"> & {
  /**
   * Unique identifier of the catalog item.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the catalog item, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the catalog item, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Reference to the underlying bare metal instance template that this catalog item references.
   *
   * @generated from field: osac.private.v1.BareMetalInstanceTemplateReference template = 5;
   */
  template?: BareMetalInstanceTemplateReference | undefined;

  /**
   * Whether this catalog item is available for provisioning. Drafts retain ordinary tenant/project visibility.
   *
   * @generated from field: bool published = 6;
   */
  published: boolean;

  /**
   * Policies that govern template parameters during resource creation.
   *
   * @generated from field: map<string, osac.private.v1.TemplateParameterPolicy> template_parameters = 9;
   */
  templateParameters: { [key: string]: TemplateParameterPolicy };

  /**
   * Policies that govern bare metal instance fields during resource creation.
   *
   * @generated from field: osac.private.v1.BareMetalInstanceCatalogItemFields fields = 10;
   */
  fields?: BareMetalInstanceCatalogItemFields | undefined;
};

/**
 * Describes the message osac.private.v1.BareMetalInstanceCatalogItem.
 * Use `create(BareMetalInstanceCatalogItemSchema)` to create a new message.
 */
export const BareMetalInstanceCatalogItemSchema: GenMessage<BareMetalInstanceCatalogItem> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_baremetal_instance_catalog_item_type, 0);

/**
 * Groups the policies for governable bare metal instance fields.
 *
 * @generated from message osac.private.v1.BareMetalInstanceCatalogItemFields
 */
export type BareMetalInstanceCatalogItemFields = Message<"osac.private.v1.BareMetalInstanceCatalogItemFields"> & {
  /**
   * @generated from field: osac.private.v1.StringFieldPolicy ssh_public_key = 1;
   */
  sshPublicKey?: StringFieldPolicy | undefined;

  /**
   * @generated from field: osac.private.v1.StringFieldPolicy user_data = 2;
   */
  userData?: StringFieldPolicy | undefined;

  /**
   * @generated from field: osac.private.v1.BareMetalInstanceRunStrategyFieldPolicy run_strategy = 3;
   */
  runStrategy?: BareMetalInstanceRunStrategyFieldPolicy | undefined;

  /**
   * @generated from field: osac.private.v1.BareMetalNetworkAttachmentListFieldPolicy network_attachments = 5;
   */
  networkAttachments?: BareMetalNetworkAttachmentListFieldPolicy | undefined;

  /**
   * @generated from field: osac.private.v1.BoolFieldPolicy auto_external_ip_attachment = 6;
   */
  autoExternalIpAttachment?: BoolFieldPolicy | undefined;

  /**
   * Policy for the bare metal instance type selected for host placement.
   *
   * @generated from field: osac.private.v1.BareMetalInstanceTypeLocalReferenceFieldPolicy instance_type = 7;
   */
  instanceType?: BareMetalInstanceTypeLocalReferenceFieldPolicy | undefined;

  /**
   * Policy for the DiskImage used to provision the instance.
   *
   * @generated from field: osac.private.v1.DiskImageReferenceFieldPolicy disk_image = 8;
   */
  diskImage?: DiskImageReferenceFieldPolicy | undefined;
};

/**
 * Describes the message osac.private.v1.BareMetalInstanceCatalogItemFields.
 * Use `create(BareMetalInstanceCatalogItemFieldsSchema)` to create a new message.
 */
export const BareMetalInstanceCatalogItemFieldsSchema: GenMessage<BareMetalInstanceCatalogItemFields> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_baremetal_instance_catalog_item_type, 1);

/**
 * Reference to a BareMetalInstanceCatalogItem resource.
 *
 * @generated from message osac.private.v1.BareMetalInstanceCatalogItemReference
 */
export type BareMetalInstanceCatalogItemReference = Message<"osac.private.v1.BareMetalInstanceCatalogItemReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string project = 3;
   */
  project: string;

  /**
   * @generated from field: bool shared = 4;
   */
  shared: boolean;
};

/**
 * Describes the message osac.private.v1.BareMetalInstanceCatalogItemReference.
 * Use `create(BareMetalInstanceCatalogItemReferenceSchema)` to create a new message.
 */
export const BareMetalInstanceCatalogItemReferenceSchema: GenMessage<BareMetalInstanceCatalogItemReference> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_baremetal_instance_catalog_item_type, 2);

