//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/capabilities_service.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { AuthnCapabilities } from "./authn_capabilities_type_pb";
import { file_osac_private_v1_authn_capabilities_type } from "./authn_capabilities_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/capabilities_service.proto.
 */
export const file_osac_private_v1_capabilities_service: GenFile = /*@__PURE__*/
  fileDesc("Cipvc2FjL3ByaXZhdGUvdjEvY2FwYWJpbGl0aWVzX3NlcnZpY2UucHJvdG8SD29zYWMucHJpdmF0ZS52MSIYChZDYXBhYmlsaXRpZXNHZXRSZXF1ZXN0IoQBChdDYXBhYmlsaXRpZXNHZXRSZXNwb25zZRIxCgVhdXRobhgBIAEoCzIiLm9zYWMucHJpdmF0ZS52MS5BdXRobkNhcGFiaWxpdGllcxI2ChBlbmFibGVkX3NlcnZpY2VzGAIgAygOMhwub3NhYy5wcml2YXRlLnYxLlNlcnZpY2VUaWVyKokBCgtTZXJ2aWNlVGllchIcChhTRVJWSUNFX1RJRVJfVU5TUEVDSUZJRUQQABIVChFTRVJWSUNFX1RJRVJfQ0FBUxABEhYKElNFUlZJQ0VfVElFUl9WTUFBUxACEhYKElNFUlZJQ0VfVElFUl9CTUFBUxADEhUKEVNFUlZJQ0VfVElFUl9NQUFTEAQyjgEKDENhcGFiaWxpdGllcxJ+CgNHZXQSJy5vc2FjLnByaXZhdGUudjEuQ2FwYWJpbGl0aWVzR2V0UmVxdWVzdBooLm9zYWMucHJpdmF0ZS52MS5DYXBhYmlsaXRpZXNHZXRSZXNwb25zZSIkgtPkkwIeEhwvYXBpL3ByaXZhdGUvdjEvY2FwYWJpbGl0aWVzQimKtRglEg5vc2FjLnB1YmxpYy52MSITcHJpdmF0ZTpmdWxmaWxsbWVudGIGcHJvdG8z", [file_cleanapi_cleanapi, file_google_api_annotations, file_osac_private_v1_authn_capabilities_type]);

/**
 * Request message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.private.v1.CapabilitiesGetRequest
 */
export type CapabilitiesGetRequest = Message<"osac.private.v1.CapabilitiesGetRequest"> & {
};

/**
 * Describes the message osac.private.v1.CapabilitiesGetRequest.
 * Use `create(CapabilitiesGetRequestSchema)` to create a new message.
 */
export const CapabilitiesGetRequestSchema: GenMessage<CapabilitiesGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_capabilities_service, 0);

/**
 * Response message for the `Get` method of the `Capabilities` service.
 *
 * @generated from message osac.private.v1.CapabilitiesGetResponse
 */
export type CapabilitiesGetResponse = Message<"osac.private.v1.CapabilitiesGetResponse"> & {
  /**
   * Authentication capabilities of the server.
   *
   * @generated from field: osac.private.v1.AuthnCapabilities authn = 1;
   */
  authn?: AuthnCapabilities | undefined;

  /**
   * Service tiers enabled in this deployment.
   *
   * @generated from field: repeated osac.private.v1.ServiceTier enabled_services = 2;
   */
  enabledServices: ServiceTier[];
};

/**
 * Describes the message osac.private.v1.CapabilitiesGetResponse.
 * Use `create(CapabilitiesGetResponseSchema)` to create a new message.
 */
export const CapabilitiesGetResponseSchema: GenMessage<CapabilitiesGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_capabilities_service, 1);

/**
 * Service tiers that can be enabled in an OSAC deployment.
 *
 * @generated from enum osac.private.v1.ServiceTier
 */
export enum ServiceTier {
  /**
   * Service tier is unknown or has not been specified.
   *
   * @generated from enum value: SERVICE_TIER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Container as a Service.
   *
   * @generated from enum value: SERVICE_TIER_CAAS = 1;
   */
  CAAS = 1,

  /**
   * Virtual Machine as a Service.
   *
   * @generated from enum value: SERVICE_TIER_VMAAS = 2;
   */
  VMAAS = 2,

  /**
   * Bare Metal as a Service.
   *
   * @generated from enum value: SERVICE_TIER_BMAAS = 3;
   */
  BMAAS = 3,

  /**
   * Metal as a Service.
   *
   * @generated from enum value: SERVICE_TIER_MAAS = 4;
   */
  MAAS = 4,
}

/**
 * Describes the enum osac.private.v1.ServiceTier.
 */
export const ServiceTierSchema: GenEnum<ServiceTier> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_capabilities_service, 0);

/**
 * Provides information about the capabilities of the server, such as the list of trusted token issuers for
 * authentication.
 *
 * @generated from service osac.private.v1.Capabilities
 */
export const Capabilities: GenService<{
  /**
   * Returns the capabilities of the server, including the authentication configuration that clients need in order to
   * obtain access tokens.
   *
   * @generated from rpc osac.private.v1.Capabilities.Get
   */
  get: {
    methodKind: "unary";
    input: typeof CapabilitiesGetRequestSchema;
    output: typeof CapabilitiesGetResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_private_v1_capabilities_service, 0);

