//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/security_rule_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/security_rule_type.proto.
 */
export const file_osac_private_v1_security_rule_type: GenFile = /*@__PURE__*/
  fileDesc("Cihvc2FjL3ByaXZhdGUvdjEvc2VjdXJpdHlfcnVsZV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEiiwMKDFNlY3VyaXR5UnVsZRIrCghwcm90b2NvbBgBIAEoDjIZLm9zYWMucHJpdmF0ZS52MS5Qcm90b2NvbBIWCglwb3J0X2Zyb20YAiABKAVIAIgBARIUCgdwb3J0X3RvGAMgASgFSAGIAQEScwoJaXB2NF9jaWRyGAQgASgJQlu6SFi6AU4KE2Nhbm9uaWNhbF9pcHY0X2NpZHISHW11c3QgYmUgYSBjYW5vbmljYWwgSVB2NCBDSURSGhh0aGlzLmlzSXBQcmVmaXgoNCwgdHJ1ZSnIAQFyAhABSAKIAQESdQoJaXB2Nl9jaWRyGAUgASgJQl26SFq6AVcKF2lwdjZfY2lkcl9ub3Rfc3VwcG9ydGVkEjBJUHY2IGFuZCBkdWFsLXN0YWNrIG5ldHdvcmtpbmcgYXJlIG5vdCBzdXBwb3J0ZWQaCnRoaXMgPT0gJydIA4gBAUIMCgpfcG9ydF9mcm9tQgoKCF9wb3J0X3RvQgwKCl9pcHY0X2NpZHJCDAoKX2lwdjZfY2lkciptCghQcm90b2NvbBIYChRQUk9UT0NPTF9VTlNQRUNJRklFRBAAEhAKDFBST1RPQ09MX1RDUBABEhAKDFBST1RPQ09MX1VEUBACEhEKDVBST1RPQ09MX0lDTVAQAxIQCgxQUk9UT0NPTF9BTEwQBEIUirUYEBIOb3NhYy5wdWJsaWMudjFiBnByb3RvMw", [file_cleanapi_cleanapi, file_buf_validate_validate]);

/**
 * Defines a single firewall rule for network traffic filtering.
 *
 * SecurityRule specifies which traffic to allow based on protocol, port ranges (for TCP/UDP), and source/
 * destination CIDR blocks. Rules are stateful - return traffic for established connections is automatically
 * allowed.
 *
 * Port ranges apply only to TCP and UDP protocols. For ICMP and ALL protocols, port fields are ignored.
 *
 * Rules currently support canonical IPv4 CIDRs only. The legacy ipv6_cidr field remains in the wire contract for
 * compatibility, but non-empty IPv6 and dual-stack requests are rejected.
 *
 * @generated from message osac.private.v1.SecurityRule
 */
export type SecurityRule = Message<"osac.private.v1.SecurityRule"> & {
  /**
   * Protocol to match for this rule.
   *
   * Use PROTOCOL_ALL to match all protocols (wildcard). Use PROTOCOL_TCP or PROTOCOL_UDP when port ranges
   * are needed. Use PROTOCOL_ICMP for ping and other ICMP traffic.
   *
   * @generated from field: osac.private.v1.Protocol protocol = 1;
   */
  protocol: Protocol;

  /**
   * Starting port number for the rule (1-65535).
   *
   * Required for tcp/udp protocols, ignored for icmp/all. For single port, set port_from = port_to.
   * Must be <= port_to. Validation enforced at service layer.
   *
   * Example: 22 (SSH), 80 (HTTP), 443 (HTTPS), 3306 (MySQL)
   *
   * @generated from field: optional int32 port_from = 2;
   */
  portFrom?: number | undefined;

  /**
   * Ending port number for the rule (1-65535).
   *
   * Required for tcp/udp protocols, ignored for icmp/all. Must be >= port_from. For single port, set
   * port_from = port_to. Validation enforced at service layer.
   *
   * Example: 22 (single port), 8000 (range 8000-9000)
   *
   * @generated from field: optional int32 port_to = 3;
   */
  portTo?: number | undefined;

  /**
   * IPv4 CIDR block for source (ingress) or destination (egress) addresses.
   *
   * Must be a canonical IPv4 CIDR with no host bits set. Use '0.0.0.0/0' to match all IPv4 addresses.
   *
   * Example: '192.168.1.0/24', '10.0.0.0/8', '0.0.0.0/0' (all IPv4)
   *
   * @generated from field: optional string ipv4_cidr = 4;
   */
  ipv4Cidr?: string | undefined;

  /**
   * Legacy IPv6 CIDR field. IPv6 and dual-stack networking are not supported; non-empty values are rejected.
   *
   * @generated from field: optional string ipv6_cidr = 5;
   */
  ipv6Cidr?: string | undefined;
};

/**
 * Describes the message osac.private.v1.SecurityRule.
 * Use `create(SecurityRuleSchema)` to create a new message.
 */
export const SecurityRuleSchema: GenMessage<SecurityRule> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_security_rule_type, 0);

/**
 * Network protocol types for SecurityRule matching.
 *
 * Determines which layer 4 protocol the rule applies to. Protocol affects whether port range fields are
 * applicable (TCP/UDP) or ignored (ICMP/ALL).
 *
 * @generated from enum osac.private.v1.Protocol
 */
export enum Protocol {
  /**
   * Unknown protocol (invalid). This should never be used in actual rules.
   *
   * @generated from enum value: PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * TCP protocol. Port ranges (port_from, port_to) are required for TCP rules.
   *
   * Used for connection-oriented protocols like HTTP, HTTPS, SSH, database connections, etc.
   *
   * @generated from enum value: PROTOCOL_TCP = 1;
   */
  TCP = 1,

  /**
   * UDP protocol. Port ranges (port_from, port_to) are required for UDP rules.
   *
   * Used for connectionless protocols like DNS, NTP, DHCP, VoIP, etc.
   *
   * @generated from enum value: PROTOCOL_UDP = 2;
   */
  UDP = 2,

  /**
   * ICMP protocol (ping and other control messages). Port ranges are not applicable.
   *
   * Used for network diagnostics (ping), error reporting, and control messages.
   *
   * @generated from enum value: PROTOCOL_ICMP = 3;
   */
  ICMP = 3,

  /**
   * All protocols (wildcard). Port ranges are not applicable.
   *
   * Matches any protocol. Useful for allowing all traffic from a trusted CIDR block or for egress rules
   * that permit all outbound traffic.
   *
   * @generated from enum value: PROTOCOL_ALL = 4;
   */
  ALL = 4,
}

/**
 * Describes the enum osac.private.v1.Protocol.
 */
export const ProtocolSchema: GenEnum<Protocol> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_security_rule_type, 0);

