//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/self_subject_access_review_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/self_subject_access_review_type.proto.
 */
export const file_osac_private_v1_self_subject_access_review_type: GenFile = /*@__PURE__*/
  fileDesc("CjVvc2FjL3ByaXZhdGUvdjEvc2VsZl9zdWJqZWN0X2FjY2Vzc19yZXZpZXdfdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIsoBChdTZWxmU3ViamVjdEFjY2Vzc1JldmlldxIrCghtZXRhZGF0YRgBIAEoCzIZLm9zYWMucHJpdmF0ZS52MS5NZXRhZGF0YRJCCgRzcGVjGAIgASgLMiwub3NhYy5wcml2YXRlLnYxLlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3U3BlY0IGukgDyAEBEj4KBnN0YXR1cxgDIAEoCzIuLm9zYWMucHJpdmF0ZS52MS5TZWxmU3ViamVjdEFjY2Vzc1Jldmlld1N0YXR1cyJ5ChtTZWxmU3ViamVjdEFjY2Vzc1Jldmlld1NwZWMSPwoHc2VydmljZRgBIAEoCUIuukgrcikQARiAATIiXm9zYWNcLnB1YmxpY1wudjFcLltBLVpdW2EtekEtWl0qJBIZCgZtZXRob2QYAiABKAlCCbpIBnIEEAEYQCJACh1TZWxmU3ViamVjdEFjY2Vzc1Jldmlld1N0YXR1cxIPCgdhbGxvd2VkGAEgASgIEg4KBnJlYXNvbhgCIAEoCUIUirUYEBIOb3NhYy5wdWJsaWMudjFiBnByb3RvMw", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_metadata_type]);

/**
 * SelfSubjectAccessReview checks whether the current user can perform an action.
 *
 * @generated from message osac.private.v1.SelfSubjectAccessReview
 */
export type SelfSubjectAccessReview = Message<"osac.private.v1.SelfSubjectAccessReview"> & {
  /**
   * Metadata contains the tenant context for the hypothetical operation.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 1;
   */
  metadata?: Metadata | undefined;

  /**
   * Spec describes information about the request being evaluated.
   *
   * @generated from field: osac.private.v1.SelfSubjectAccessReviewSpec spec = 2;
   */
  spec?: SelfSubjectAccessReviewSpec | undefined;

  /**
   * Status is filled in by the server and indicates whether the request is allowed or not.
   *
   * @generated from field: osac.private.v1.SelfSubjectAccessReviewStatus status = 3;
   */
  status?: SelfSubjectAccessReviewStatus | undefined;
};

/**
 * Describes the message osac.private.v1.SelfSubjectAccessReview.
 * Use `create(SelfSubjectAccessReviewSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewSchema: GenMessage<SelfSubjectAccessReview> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_self_subject_access_review_type, 0);

/**
 * SelfSubjectAccessReviewSpec describes the hypothetical operation to check.
 *
 * @generated from message osac.private.v1.SelfSubjectAccessReviewSpec
 */
export type SelfSubjectAccessReviewSpec = Message<"osac.private.v1.SelfSubjectAccessReviewSpec"> & {
  /**
   * service is the full OSAC service name to check permission for
   * (e.g., "osac.public.v1.Clusters", "osac.public.v1.ComputeInstances", "osac.public.v1.VirtualNetworks").
   * Must be a valid fully-qualified OSAC service name.
   *
   * @generated from field: string service = 1;
   */
  service: string;

  /**
   * method is the operation to check (e.g., Create, Get, List, Update, Delete).
   * Method names must match gRPC method naming conventions (capitalized).
   * Valid methods are determined by the service definition and validated at runtime
   * using protobuf reflection.
   *
   * @generated from field: string method = 2;
   */
  method: string;
};

/**
 * Describes the message osac.private.v1.SelfSubjectAccessReviewSpec.
 * Use `create(SelfSubjectAccessReviewSpecSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewSpecSchema: GenMessage<SelfSubjectAccessReviewSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_self_subject_access_review_type, 1);

/**
 * SelfSubjectAccessReviewStatus describes the result of the permission check.
 *
 * @generated from message osac.private.v1.SelfSubjectAccessReviewStatus
 */
export type SelfSubjectAccessReviewStatus = Message<"osac.private.v1.SelfSubjectAccessReviewStatus"> & {
  /**
   * Allowed is true if the user would be authorized to perform the requested operation.
   *
   * @generated from field: bool allowed = 1;
   */
  allowed: boolean;

  /**
   * Reason describes why the request was denied (reserved for future use).
   * v1 implementation: always empty — current OPA policy does not export denial reasons.
   * Future enhancement: extract structured denial reasons from OPA policy output.
   *
   * @generated from field: string reason = 2;
   */
  reason: string;
};

/**
 * Describes the message osac.private.v1.SelfSubjectAccessReviewStatus.
 * Use `create(SelfSubjectAccessReviewStatusSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewStatusSchema: GenMessage<SelfSubjectAccessReviewStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_self_subject_access_review_type, 2);

