//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/self_subject_access_review_service.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { SelfSubjectAccessReview } from "./self_subject_access_review_type_pb";
import { file_osac_private_v1_self_subject_access_review_type } from "./self_subject_access_review_type_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/self_subject_access_review_service.proto.
 */
export const file_osac_private_v1_self_subject_access_review_service: GenFile = /*@__PURE__*/
  fileDesc("Cjhvc2FjL3ByaXZhdGUvdjEvc2VsZl9zdWJqZWN0X2FjY2Vzc19yZXZpZXdfc2VydmljZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxImEKJVNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3c0NyZWF0ZVJlcXVlc3QSOAoGb2JqZWN0GAEgASgLMigub3NhYy5wcml2YXRlLnYxLlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3ImIKJlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3c0NyZWF0ZVJlc3BvbnNlEjgKBm9iamVjdBgBIAEoCzIoLm9zYWMucHJpdmF0ZS52MS5TZWxmU3ViamVjdEFjY2Vzc1JldmlldzLbAQoYU2VsZlN1YmplY3RBY2Nlc3NSZXZpZXdzEr4BCgZDcmVhdGUSNi5vc2FjLnByaXZhdGUudjEuU2VsZlN1YmplY3RBY2Nlc3NSZXZpZXdzQ3JlYXRlUmVxdWVzdBo3Lm9zYWMucHJpdmF0ZS52MS5TZWxmU3ViamVjdEFjY2Vzc1Jldmlld3NDcmVhdGVSZXNwb25zZSJDgtPkkwI9OgZvYmplY3RiBm9iamVjdCIrL2FwaS9wcml2YXRlL3YxL3NlbGZfc3ViamVjdF9hY2Nlc3NfcmV2aWV3c0IpirUYJRIOb3NhYy5wdWJsaWMudjEiE3ByaXZhdGU6ZnVsZmlsbG1lbnRiBnByb3RvMw", [file_google_api_annotations, file_osac_private_v1_self_subject_access_review_type, file_cleanapi_cleanapi]);

/**
 * @generated from message osac.private.v1.SelfSubjectAccessReviewsCreateRequest
 */
export type SelfSubjectAccessReviewsCreateRequest = Message<"osac.private.v1.SelfSubjectAccessReviewsCreateRequest"> & {
  /**
   * @generated from field: osac.private.v1.SelfSubjectAccessReview object = 1;
   */
  object?: SelfSubjectAccessReview | undefined;
};

/**
 * Describes the message osac.private.v1.SelfSubjectAccessReviewsCreateRequest.
 * Use `create(SelfSubjectAccessReviewsCreateRequestSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewsCreateRequestSchema: GenMessage<SelfSubjectAccessReviewsCreateRequest> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_self_subject_access_review_service, 0);

/**
 * @generated from message osac.private.v1.SelfSubjectAccessReviewsCreateResponse
 */
export type SelfSubjectAccessReviewsCreateResponse = Message<"osac.private.v1.SelfSubjectAccessReviewsCreateResponse"> & {
  /**
   * @generated from field: osac.private.v1.SelfSubjectAccessReview object = 1;
   */
  object?: SelfSubjectAccessReview | undefined;
};

/**
 * Describes the message osac.private.v1.SelfSubjectAccessReviewsCreateResponse.
 * Use `create(SelfSubjectAccessReviewsCreateResponseSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewsCreateResponseSchema: GenMessage<SelfSubjectAccessReviewsCreateResponse> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_self_subject_access_review_service, 1);

/**
 * SelfSubjectAccessReviews service allows users to check their own permissions.
 *
 * @generated from service osac.private.v1.SelfSubjectAccessReviews
 */
export const SelfSubjectAccessReviews: GenService<{
  /**
   * Create evaluates the permission check and returns the result immediately.
   * This is a create-only service with no List, Get, Update, or Delete methods.
   *
   * @generated from rpc osac.private.v1.SelfSubjectAccessReviews.Create
   */
  create: {
    methodKind: "unary";
    input: typeof SelfSubjectAccessReviewsCreateRequestSchema;
    output: typeof SelfSubjectAccessReviewsCreateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_private_v1_self_subject_access_review_service, 0);

