apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.12-nightly.20260828.5744882.49.1
appVersion: 0.0.12-nightly.20260828.5744882.49.1
