apiVersion: v2
name: bare-metal-fulfillment-operator-crds
description: CRDs for the Bare Metal Fulfillment Operator
type: application
version: 0.0.12-nightly.20260903.e6e4f62.67.1
appVersion: 0.0.12-nightly.20260903.e6e4f62.67.1
