apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.20-nightly.20261007.007c36c.121.1
appVersion: 0.0.20-nightly.20261007.007c36c.121.1
