apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.20-nightly.20261008.47fbd58.122.1
appVersion: 0.0.20-nightly.20261008.47fbd58.122.1
