apiVersion: v2
name: osac-aap
description: OSAC AAP integration - bootstrap and configuration
type: application
version: 0.0.19-nightly.20261004.c23ed2d.118.1
appVersion: 0.0.19-nightly.20261004.c23ed2d.118.1
