{{/*
Copyright (c) 2026 Red Hat Inc.

Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
*/}}

apiVersion: v1
kind: Pod
metadata:
  namespace: {{ .Release.Namespace }}
  name: openbao
  labels:
    app: openbao
spec:
  {{ if .Values.caBundle.configMap }}
  volumes:
  - name: ca-bundle
    configMap:
      name: {{ .Values.caBundle.configMap }}
  {{ end }}
  containers:
  - name: server
    image: "{{ .Values.images.openbao }}"
    imagePullPolicy: IfNotPresent
    command:
    - bao
    - server
    - -dev
    - -dev-root-token-id={{ required "dev.rootToken must be set" .Values.dev.rootToken }}
    - -dev-listen-address={{ .Values.dev.listenAddress }}
    {{ if .Values.caBundle.configMap }}
    env:
    - name: BAO_CACERT
      value: /etc/openbao/ca/bundle.pem
    volumeMounts:
    - name: ca-bundle
      mountPath: /etc/openbao/ca
      readOnly: true
    {{ end }}
    ports:
    - name: api
      protocol: TCP
      containerPort: 8200
    readinessProbe:
      httpGet:
        path: /v1/sys/health
        port: api
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 5
    livenessProbe:
      httpGet:
        path: /v1/sys/health
        port: api
        scheme: HTTP
      initialDelaySeconds: 10
      periodSeconds: 10
