// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/bare-metal-fulfillment-operator/internal/baremetalhost (interfaces: BMHLifecycleManager)
//
// Generated by this command:
//
//	mockgen -destination=bmh_lifecycle_manager_mock.go -package=baremetalhost . BMHLifecycleManager
//

// Package baremetalhost is a generated GoMock package.
package baremetalhost

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBMHLifecycleManager is a mock of BMHLifecycleManager interface.
type MockBMHLifecycleManager struct {
	ctrl     *gomock.Controller
	recorder *MockBMHLifecycleManagerMockRecorder
	isgomock struct{}
}

// MockBMHLifecycleManagerMockRecorder is the mock recorder for MockBMHLifecycleManager.
type MockBMHLifecycleManagerMockRecorder struct {
	mock *MockBMHLifecycleManager
}

// NewMockBMHLifecycleManager creates a new mock instance.
func NewMockBMHLifecycleManager(ctrl *gomock.Controller) *MockBMHLifecycleManager {
	mock := &MockBMHLifecycleManager{ctrl: ctrl}
	mock.recorder = &MockBMHLifecycleManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBMHLifecycleManager) EXPECT() *MockBMHLifecycleManagerMockRecorder {
	return m.recorder
}

// BMHExists mocks base method.
func (m *MockBMHLifecycleManager) BMHExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BMHExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BMHExists indicates an expected call of BMHExists.
func (mr *MockBMHLifecycleManagerMockRecorder) BMHExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BMHExists", reflect.TypeOf((*MockBMHLifecycleManager)(nil).BMHExists), ctx, name)
}

// CreateBMH mocks base method.
func (m *MockBMHLifecycleManager) CreateBMH(ctx context.Context, params CreateParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBMH", ctx, params)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBMH indicates an expected call of CreateBMH.
func (mr *MockBMHLifecycleManagerMockRecorder) CreateBMH(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBMH", reflect.TypeOf((*MockBMHLifecycleManager)(nil).CreateBMH), ctx, params)
}

// DeleteBMCSecret mocks base method.
func (m *MockBMHLifecycleManager) DeleteBMCSecret(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBMCSecret", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBMCSecret indicates an expected call of DeleteBMCSecret.
func (mr *MockBMHLifecycleManagerMockRecorder) DeleteBMCSecret(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBMCSecret", reflect.TypeOf((*MockBMHLifecycleManager)(nil).DeleteBMCSecret), ctx, name)
}

// DeleteBMH mocks base method.
func (m *MockBMHLifecycleManager) DeleteBMH(ctx context.Context, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBMH", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBMH indicates an expected call of DeleteBMH.
func (mr *MockBMHLifecycleManagerMockRecorder) DeleteBMH(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBMH", reflect.TypeOf((*MockBMHLifecycleManager)(nil).DeleteBMH), ctx, name)
}

// EnsureBMCSecret mocks base method.
func (m *MockBMHLifecycleManager) EnsureBMCSecret(ctx context.Context, name, username, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsureBMCSecret", ctx, name, username, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsureBMCSecret indicates an expected call of EnsureBMCSecret.
func (mr *MockBMHLifecycleManagerMockRecorder) EnsureBMCSecret(ctx, name, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsureBMCSecret", reflect.TypeOf((*MockBMHLifecycleManager)(nil).EnsureBMCSecret), ctx, name, username, password)
}

// GetHardwareNICs mocks base method.
func (m *MockBMHLifecycleManager) GetHardwareNICs(ctx context.Context, name string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHardwareNICs", ctx, name)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHardwareNICs indicates an expected call of GetHardwareNICs.
func (mr *MockBMHLifecycleManagerMockRecorder) GetHardwareNICs(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHardwareNICs", reflect.TypeOf((*MockBMHLifecycleManager)(nil).GetHardwareNICs), ctx, name)
}

// IsBMHReady mocks base method.
func (m *MockBMHLifecycleManager) IsBMHReady(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBMHReady", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBMHReady indicates an expected call of IsBMHReady.
func (mr *MockBMHLifecycleManagerMockRecorder) IsBMHReady(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBMHReady", reflect.TypeOf((*MockBMHLifecycleManager)(nil).IsBMHReady), ctx, name)
}

// Namespace mocks base method.
func (m *MockBMHLifecycleManager) Namespace() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Namespace")
	ret0, _ := ret[0].(string)
	return ret0
}

// Namespace indicates an expected call of Namespace.
func (mr *MockBMHLifecycleManagerMockRecorder) Namespace() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Namespace", reflect.TypeOf((*MockBMHLifecycleManager)(nil).Namespace))
}
