//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/security_groups_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { SecurityGroup } from "./security_group_type_pb";
import { file_osac_public_v1_security_group_type } from "./security_group_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/security_groups_service.proto.
 */
export const file_osac_public_v1_security_groups_service: GenFile = /*@__PURE__*/
  fileDesc("Cixvc2FjL3B1YmxpYy92MS9zZWN1cml0eV9ncm91cHNfc2VydmljZS5wcm90bxIOb3NhYy5wdWJsaWMudjEilwEKGVNlY3VyaXR5R3JvdXBzTGlzdFJlcXVlc3QSEwoGb2Zmc2V0GAEgASgFSACIAQESEgoFbGltaXQYAiABKAVIAYgBARITCgZmaWx0ZXIYAyABKAlIAogBARISCgVvcmRlchgEIAEoCUgDiAEBQgkKB19vZmZzZXRCCAoGX2xpbWl0QgkKB19maWx0ZXJCCAoGX29yZGVyImcKGlNlY3VyaXR5R3JvdXBzTGlzdFJlc3BvbnNlEgwKBHNpemUYASABKAUSDQoFdG90YWwYAiABKAUSLAoFaXRlbXMYAyADKAsyHS5vc2FjLnB1YmxpYy52MS5TZWN1cml0eUdyb3VwIiYKGFNlY3VyaXR5R3JvdXBzR2V0UmVxdWVzdBIKCgJpZBgBIAEoCSJKChlTZWN1cml0eUdyb3Vwc0dldFJlc3BvbnNlEi0KBm9iamVjdBgBIAEoCzIdLm9zYWMucHVibGljLnYxLlNlY3VyaXR5R3JvdXAiTAobU2VjdXJpdHlHcm91cHNDcmVhdGVSZXF1ZXN0Ei0KBm9iamVjdBgBIAEoCzIdLm9zYWMucHVibGljLnYxLlNlY3VyaXR5R3JvdXAiTQocU2VjdXJpdHlHcm91cHNDcmVhdGVSZXNwb25zZRItCgZvYmplY3QYASABKAsyHS5vc2FjLnB1YmxpYy52MS5TZWN1cml0eUdyb3VwIikKG1NlY3VyaXR5R3JvdXBzRGVsZXRlUmVxdWVzdBIKCgJpZBgBIAEoCSIeChxTZWN1cml0eUdyb3Vwc0RlbGV0ZVJlc3BvbnNlMu8ECg5TZWN1cml0eUdyb3VwcxKKAQoETGlzdBIpLm9zYWMucHVibGljLnYxLlNlY3VyaXR5R3JvdXBzTGlzdFJlcXVlc3QaKi5vc2FjLnB1YmxpYy52MS5TZWN1cml0eUdyb3Vwc0xpc3RSZXNwb25zZSIrgtPkkwIlEiMvYXBpL2Z1bGZpbGxtZW50L3YxL3NlY3VyaXR5X2dyb3VwcxKUAQoDR2V0Eigub3NhYy5wdWJsaWMudjEuU2VjdXJpdHlHcm91cHNHZXRSZXF1ZXN0Gikub3NhYy5wdWJsaWMudjEuU2VjdXJpdHlHcm91cHNHZXRSZXNwb25zZSI4gtPkkwIyYgZvYmplY3QSKC9hcGkvZnVsZmlsbG1lbnQvdjEvc2VjdXJpdHlfZ3JvdXBzL3tpZH0SoAEKBkNyZWF0ZRIrLm9zYWMucHVibGljLnYxLlNlY3VyaXR5R3JvdXBzQ3JlYXRlUmVxdWVzdBosLm9zYWMucHVibGljLnYxLlNlY3VyaXR5R3JvdXBzQ3JlYXRlUmVzcG9uc2UiO4LT5JMCNToGb2JqZWN0YgZvYmplY3QiIy9hcGkvZnVsZmlsbG1lbnQvdjEvc2VjdXJpdHlfZ3JvdXBzEpUBCgZEZWxldGUSKy5vc2FjLnB1YmxpYy52MS5TZWN1cml0eUdyb3Vwc0RlbGV0ZVJlcXVlc3QaLC5vc2FjLnB1YmxpYy52MS5TZWN1cml0eUdyb3Vwc0RlbGV0ZVJlc3BvbnNlIjCC0+STAioqKC9hcGkvZnVsZmlsbG1lbnQvdjEvc2VjdXJpdHlfZ3JvdXBzL3tpZH1iBnByb3RvMw", [file_google_api_annotations, file_osac_public_v1_security_group_type]);

/**
 * @generated from message osac.public.v1.SecurityGroupsListRequest
 */
export type SecurityGroupsListRequest = Message<"osac.public.v1.SecurityGroupsListRequest"> & {
  /**
   * Index of the first result. If not specified the default value will be zero.
   *
   * @generated from field: optional int32 offset = 1;
   */
  offset?: number | undefined;

  /**
   * Maximum number of results to be returned by the server. When not specified all the results will be returned. Note
   * that there may not be enough results to return, and that the server may decide, for performance reasons, to return
   * less results than requested.
   *
   * @generated from field: optional int32 limit = 2;
   */
  limit?: number | undefined;

  /**
   * Filter criteria.
   *
   * The value of this parameter is a [CEL](https://cel.dev) expression used to select which objects to return. The
   * built-in `this` variable refers to the object being tested and `now` refers to the current date and time. If the
   * expression evaluates to `true` the object is included in the results. For example, to retrieve all security groups
   * with names starting with `web-servers`:
   *
   *     this.metadata.name.startsWith("web-servers")
   *
   * If this isn't provided, or if the value is empty, then all the security groups that the user has permission to see
   * will be returned. Not all CEL constructs are currently supported for implementation reasons; see the filter
   * documentation (docs/FILTER.md) for the full details.
   *
   * @generated from field: optional string filter = 3;
   */
  filter?: string | undefined;

  /**
   * Order criteria.
   *
   * The syntax of this parameter is similar to the syntax of the _order by_ clause of a SQL statement, but using the
   * names of the attributes of the security group instead of the names of the columns of a table. For example, in order to
   * sort the security groups descending by creation time the value should be:
   *
   *     metadata.created_at desc
   *
   * If the parameter isn't provided, or if the value is empty, then the order of the results is undefined.
   *
   * @generated from field: optional string order = 4;
   */
  order?: string | undefined;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsListRequest.
 * Use `create(SecurityGroupsListRequestSchema)` to create a new message.
 */
export const SecurityGroupsListRequestSchema: GenMessage<SecurityGroupsListRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 0);

/**
 * @generated from message osac.public.v1.SecurityGroupsListResponse
 */
export type SecurityGroupsListResponse = Message<"osac.public.v1.SecurityGroupsListResponse"> & {
  /**
   * Actual number of items returned. Note that this may be smaller than the value requested in the `limit` parameter
   * of the request if there are not enough items, or if the system decides that returning that number of items isn't
   * feasible or convenient for performance reasons.
   *
   * @generated from field: int32 size = 1;
   */
  size: number;

  /**
   * Total number of items of the collection that match the search criteria, regardless of the number of results
   * requested with the `limit` parameter.
   *
   * @generated from field: int32 total = 2;
   */
  total: number;

  /**
   * List of results.
   *
   * @generated from field: repeated osac.public.v1.SecurityGroup items = 3;
   */
  items: SecurityGroup[];
};

/**
 * Describes the message osac.public.v1.SecurityGroupsListResponse.
 * Use `create(SecurityGroupsListResponseSchema)` to create a new message.
 */
export const SecurityGroupsListResponseSchema: GenMessage<SecurityGroupsListResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 1);

/**
 * @generated from message osac.public.v1.SecurityGroupsGetRequest
 */
export type SecurityGroupsGetRequest = Message<"osac.public.v1.SecurityGroupsGetRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsGetRequest.
 * Use `create(SecurityGroupsGetRequestSchema)` to create a new message.
 */
export const SecurityGroupsGetRequestSchema: GenMessage<SecurityGroupsGetRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 2);

/**
 * @generated from message osac.public.v1.SecurityGroupsGetResponse
 */
export type SecurityGroupsGetResponse = Message<"osac.public.v1.SecurityGroupsGetResponse"> & {
  /**
   * @generated from field: osac.public.v1.SecurityGroup object = 1;
   */
  object?: SecurityGroup | undefined;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsGetResponse.
 * Use `create(SecurityGroupsGetResponseSchema)` to create a new message.
 */
export const SecurityGroupsGetResponseSchema: GenMessage<SecurityGroupsGetResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 3);

/**
 * @generated from message osac.public.v1.SecurityGroupsCreateRequest
 */
export type SecurityGroupsCreateRequest = Message<"osac.public.v1.SecurityGroupsCreateRequest"> & {
  /**
   * @generated from field: osac.public.v1.SecurityGroup object = 1;
   */
  object?: SecurityGroup | undefined;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsCreateRequest.
 * Use `create(SecurityGroupsCreateRequestSchema)` to create a new message.
 */
export const SecurityGroupsCreateRequestSchema: GenMessage<SecurityGroupsCreateRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 4);

/**
 * @generated from message osac.public.v1.SecurityGroupsCreateResponse
 */
export type SecurityGroupsCreateResponse = Message<"osac.public.v1.SecurityGroupsCreateResponse"> & {
  /**
   * @generated from field: osac.public.v1.SecurityGroup object = 1;
   */
  object?: SecurityGroup | undefined;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsCreateResponse.
 * Use `create(SecurityGroupsCreateResponseSchema)` to create a new message.
 */
export const SecurityGroupsCreateResponseSchema: GenMessage<SecurityGroupsCreateResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 5);

/**
 * @generated from message osac.public.v1.SecurityGroupsDeleteRequest
 */
export type SecurityGroupsDeleteRequest = Message<"osac.public.v1.SecurityGroupsDeleteRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message osac.public.v1.SecurityGroupsDeleteRequest.
 * Use `create(SecurityGroupsDeleteRequestSchema)` to create a new message.
 */
export const SecurityGroupsDeleteRequestSchema: GenMessage<SecurityGroupsDeleteRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 6);

/**
 * @generated from message osac.public.v1.SecurityGroupsDeleteResponse
 */
export type SecurityGroupsDeleteResponse = Message<"osac.public.v1.SecurityGroupsDeleteResponse"> & {
};

/**
 * Describes the message osac.public.v1.SecurityGroupsDeleteResponse.
 * Use `create(SecurityGroupsDeleteResponseSchema)` to create a new message.
 */
export const SecurityGroupsDeleteResponseSchema: GenMessage<SecurityGroupsDeleteResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_security_groups_service, 7);

/**
 * @generated from service osac.public.v1.SecurityGroups
 */
export const SecurityGroups: GenService<{
  /**
   * Retrieves the list of security groups.
   *
   * @generated from rpc osac.public.v1.SecurityGroups.List
   */
  list: {
    methodKind: "unary";
    input: typeof SecurityGroupsListRequestSchema;
    output: typeof SecurityGroupsListResponseSchema;
  },
  /**
   * Retrieves the details of one specific security group.
   *
   * @generated from rpc osac.public.v1.SecurityGroups.Get
   */
  get: {
    methodKind: "unary";
    input: typeof SecurityGroupsGetRequestSchema;
    output: typeof SecurityGroupsGetResponseSchema;
  },
  /**
   * Creates a new security group.
   *
   * @generated from rpc osac.public.v1.SecurityGroups.Create
   */
  create: {
    methodKind: "unary";
    input: typeof SecurityGroupsCreateRequestSchema;
    output: typeof SecurityGroupsCreateResponseSchema;
  },
  /**
   * Deletes a security group.
   *
   * @generated from rpc osac.public.v1.SecurityGroups.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof SecurityGroupsDeleteRequestSchema;
    output: typeof SecurityGroupsDeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_security_groups_service, 0);

