//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/self_subject_access_review_service.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb";
import type { SelfSubjectAccessReview } from "./self_subject_access_review_type_pb";
import { file_osac_public_v1_self_subject_access_review_type } from "./self_subject_access_review_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/self_subject_access_review_service.proto.
 */
export const file_osac_public_v1_self_subject_access_review_service: GenFile = /*@__PURE__*/
  fileDesc("Cjdvc2FjL3B1YmxpYy92MS9zZWxmX3N1YmplY3RfYWNjZXNzX3Jldmlld19zZXJ2aWNlLnByb3RvEg5vc2FjLnB1YmxpYy52MSJgCiVTZWxmU3ViamVjdEFjY2Vzc1Jldmlld3NDcmVhdGVSZXF1ZXN0EjcKBm9iamVjdBgBIAEoCzInLm9zYWMucHVibGljLnYxLlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3ImEKJlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3c0NyZWF0ZVJlc3BvbnNlEjcKBm9iamVjdBgBIAEoCzInLm9zYWMucHVibGljLnYxLlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3Mt0BChhTZWxmU3ViamVjdEFjY2Vzc1Jldmlld3MSwAEKBkNyZWF0ZRI1Lm9zYWMucHVibGljLnYxLlNlbGZTdWJqZWN0QWNjZXNzUmV2aWV3c0NyZWF0ZVJlcXVlc3QaNi5vc2FjLnB1YmxpYy52MS5TZWxmU3ViamVjdEFjY2Vzc1Jldmlld3NDcmVhdGVSZXNwb25zZSJHgtPkkwJBOgZvYmplY3RiBm9iamVjdCIvL2FwaS9mdWxmaWxsbWVudC92MS9zZWxmX3N1YmplY3RfYWNjZXNzX3Jldmlld3NiBnByb3RvMw", [file_google_api_annotations, file_osac_public_v1_self_subject_access_review_type]);

/**
 * @generated from message osac.public.v1.SelfSubjectAccessReviewsCreateRequest
 */
export type SelfSubjectAccessReviewsCreateRequest = Message<"osac.public.v1.SelfSubjectAccessReviewsCreateRequest"> & {
  /**
   * @generated from field: osac.public.v1.SelfSubjectAccessReview object = 1;
   */
  object?: SelfSubjectAccessReview | undefined;
};

/**
 * Describes the message osac.public.v1.SelfSubjectAccessReviewsCreateRequest.
 * Use `create(SelfSubjectAccessReviewsCreateRequestSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewsCreateRequestSchema: GenMessage<SelfSubjectAccessReviewsCreateRequest> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_self_subject_access_review_service, 0);

/**
 * @generated from message osac.public.v1.SelfSubjectAccessReviewsCreateResponse
 */
export type SelfSubjectAccessReviewsCreateResponse = Message<"osac.public.v1.SelfSubjectAccessReviewsCreateResponse"> & {
  /**
   * @generated from field: osac.public.v1.SelfSubjectAccessReview object = 1;
   */
  object?: SelfSubjectAccessReview | undefined;
};

/**
 * Describes the message osac.public.v1.SelfSubjectAccessReviewsCreateResponse.
 * Use `create(SelfSubjectAccessReviewsCreateResponseSchema)` to create a new message.
 */
export const SelfSubjectAccessReviewsCreateResponseSchema: GenMessage<SelfSubjectAccessReviewsCreateResponse> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_self_subject_access_review_service, 1);

/**
 * SelfSubjectAccessReviews service allows users to check their own permissions.
 *
 * @generated from service osac.public.v1.SelfSubjectAccessReviews
 */
export const SelfSubjectAccessReviews: GenService<{
  /**
   * Create evaluates the permission check and returns the result immediately.
   * This is a create-only service with no List, Get, Update, or Delete methods.
   *
   * @generated from rpc osac.public.v1.SelfSubjectAccessReviews.Create
   */
  create: {
    methodKind: "unary";
    input: typeof SelfSubjectAccessReviewsCreateRequestSchema;
    output: typeof SelfSubjectAccessReviewsCreateResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_osac_public_v1_self_subject_access_review_service, 0);

