---
- name: Delete an ExternalIPPool resource
  hosts: localhost
  gather_facts: false

  vars:
    external_ip_pool: "{{ osac_job_vars.resource }}"
    external_ip_pool_name: "{{ osac_job_vars.resource.metadata.name }}"
    implementation_strategy: >-
      {{ osac_job_vars.resource.metadata.annotations
         ['osac.openshift.io/implementation-strategy'] }}
    template_parameters: {}

  pre_tasks:
    - name: Show resource metadata
      ansible.builtin.debug:
        var: osac_job_vars.resource.metadata

  tasks:
    - name: Display ExternalIPPool information
      ansible.builtin.debug:
        msg:
          - "Deleting ExternalIPPool: {{ external_ip_pool_name }}"
          - "Implementation strategy: {{ implementation_strategy }}"

    - name: Call the selected ExternalIPPool role
      ansible.builtin.include_role:
        name: "{{ template_id_override | default('osac.templates.' + (implementation_strategy | replace('-', '_'))) }}"
        tasks_from: delete_external_ip_pool
