---
- name: Create a VirtualNetwork resource
  hosts: localhost
  gather_facts: false

  vars:
    virtual_network: "{{ osac_job_vars.resource }}"
    virtual_network_name: "{{ osac_job_vars.resource.metadata.name }}"
    # Implementation strategy set by fulfillment-service in VirtualNetwork spec
    implementation_strategy: "{{ osac_job_vars.resource.spec.implementationStrategy }}"
    template_parameters: {}

  pre_tasks:
    - name: Show resource metadata
      ansible.builtin.debug:
        var: osac_job_vars.resource.metadata

  tasks:
    - name: Display VirtualNetwork information
      ansible.builtin.debug:
        msg:
          - "VirtualNetwork name: {{ virtual_network_name }}"
          - "Implementation strategy: {{ implementation_strategy }}"
          - "Template parameters: {{ template_parameters }}"

    - name: Call the selected VirtualNetwork role
      ansible.builtin.include_role:
        name: "osac.templates.{{ implementation_strategy }}"
        tasks_from: create_virtual_network
