---
- name: Attach an ExternalIP to a target resource
  hosts: localhost
  gather_facts: false

  vars:
    external_ip_attachment: "{{ osac_job_vars.resource }}"
    implementation_strategy: >-
      {{ osac_job_vars.resource.metadata.annotations['osac.openshift.io/implementation-strategy'] }}
    template_parameters: {}

  pre_tasks:
    - name: Show resource metadata
      ansible.builtin.debug:
        var: osac_job_vars.resource.metadata

  tasks:
    - name: Display ExternalIP attach information
      ansible.builtin.debug:
        msg:
          - "ExternalIP attachment name: {{ osac_job_vars.resource.metadata.name }}"
          - "Implementation strategy: {{ implementation_strategy }}"

    - name: Call the selected ExternalIP attach role
      ansible.builtin.include_role:
        name: "{{ template_id_override | default('osac.templates.' + (implementation_strategy | replace('-', '_'))) }}"
        tasks_from: attach_external_ip
