// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/reflection (interfaces: Helper)
//
// Generated by this command:
//
//	mockgen -destination=reflection_helper_mock.go -package=reflection . Helper
//

// Package reflection is a generated GoMock package.
package reflection

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockHelper is a mock of Helper interface.
type MockHelper struct {
	ctrl     *gomock.Controller
	recorder *MockHelperMockRecorder
	isgomock struct{}
}

// MockHelperMockRecorder is the mock recorder for MockHelper.
type MockHelperMockRecorder struct {
	mock *MockHelper
}

// NewMockHelper creates a new mock instance.
func NewMockHelper(ctrl *gomock.Controller) *MockHelper {
	mock := &MockHelper{ctrl: ctrl}
	mock.recorder = &MockHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHelper) EXPECT() *MockHelperMockRecorder {
	return m.recorder
}

// Lookup mocks base method.
func (m *MockHelper) Lookup(objectType string) ObjectHelper {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", objectType)
	ret0, _ := ret[0].(ObjectHelper)
	return ret0
}

// Lookup indicates an expected call of Lookup.
func (mr *MockHelperMockRecorder) Lookup(objectType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockHelper)(nil).Lookup), objectType)
}

// Names mocks base method.
func (m *MockHelper) Names() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Names")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Names indicates an expected call of Names.
func (mr *MockHelperMockRecorder) Names() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Names", reflect.TypeOf((*MockHelper)(nil).Names))
}

// Plurals mocks base method.
func (m *MockHelper) Plurals() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plurals")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Plurals indicates an expected call of Plurals.
func (mr *MockHelperMockRecorder) Plurals() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plurals", reflect.TypeOf((*MockHelper)(nil).Plurals))
}

// Singulars mocks base method.
func (m *MockHelper) Singulars() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Singulars")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Singulars indicates an expected call of Singulars.
func (mr *MockHelperMockRecorder) Singulars() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Singulars", reflect.TypeOf((*MockHelper)(nil).Singulars))
}
