// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/fulfillment-service/internal/reflection (interfaces: ObjectHelper)
//
// Generated by this command:
//
//	mockgen -destination=reflection_object_helper_mock.go -package=reflection . ObjectHelper
//

// Package reflection is a generated GoMock package.
package reflection

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	proto "google.golang.org/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
)

// MockObjectHelper is a mock of ObjectHelper interface.
type MockObjectHelper struct {
	ctrl     *gomock.Controller
	recorder *MockObjectHelperMockRecorder
	isgomock struct{}
}

// MockObjectHelperMockRecorder is the mock recorder for MockObjectHelper.
type MockObjectHelperMockRecorder struct {
	mock *MockObjectHelper
}

// NewMockObjectHelper creates a new mock instance.
func NewMockObjectHelper(ctrl *gomock.Controller) *MockObjectHelper {
	mock := &MockObjectHelper{ctrl: ctrl}
	mock.recorder = &MockObjectHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObjectHelper) EXPECT() *MockObjectHelperMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockObjectHelper) Create(ctx context.Context, object proto.Message) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, object)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockObjectHelperMockRecorder) Create(ctx, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockObjectHelper)(nil).Create), ctx, object)
}

// Delete mocks base method.
func (m *MockObjectHelper) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockObjectHelperMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockObjectHelper)(nil).Delete), ctx, id)
}

// Descriptor mocks base method.
func (m *MockObjectHelper) Descriptor() protoreflect.MessageDescriptor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Descriptor")
	ret0, _ := ret[0].(protoreflect.MessageDescriptor)
	return ret0
}

// Descriptor indicates an expected call of Descriptor.
func (mr *MockObjectHelperMockRecorder) Descriptor() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Descriptor", reflect.TypeOf((*MockObjectHelper)(nil).Descriptor))
}

// FindObject mocks base method.
func (m *MockObjectHelper) FindObject(ctx context.Context, ref string, console Renderer) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindObject", ctx, ref, console)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindObject indicates an expected call of FindObject.
func (mr *MockObjectHelperMockRecorder) FindObject(ctx, ref, console any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindObject", reflect.TypeOf((*MockObjectHelper)(nil).FindObject), ctx, ref, console)
}

// FullName mocks base method.
func (m *MockObjectHelper) FullName() protoreflect.FullName {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FullName")
	ret0, _ := ret[0].(protoreflect.FullName)
	return ret0
}

// FullName indicates an expected call of FullName.
func (mr *MockObjectHelperMockRecorder) FullName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FullName", reflect.TypeOf((*MockObjectHelper)(nil).FullName))
}

// Get mocks base method.
func (m *MockObjectHelper) Get(ctx context.Context, id string) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockObjectHelperMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockObjectHelper)(nil).Get), ctx, id)
}

// GetId mocks base method.
func (m *MockObjectHelper) GetId(object proto.Message) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetId", object)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetId indicates an expected call of GetId.
func (mr *MockObjectHelperMockRecorder) GetId(object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetId", reflect.TypeOf((*MockObjectHelper)(nil).GetId), object)
}

// GetMetadata mocks base method.
func (m *MockObjectHelper) GetMetadata(object proto.Message) Metadata {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", object)
	ret0, _ := ret[0].(Metadata)
	return ret0
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockObjectHelperMockRecorder) GetMetadata(object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockObjectHelper)(nil).GetMetadata), object)
}

// GetName mocks base method.
func (m *MockObjectHelper) GetName(object proto.Message) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName", object)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockObjectHelperMockRecorder) GetName(object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockObjectHelper)(nil).GetName), object)
}

// GetTenant mocks base method.
func (m *MockObjectHelper) GetTenant(object proto.Message) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTenant", object)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTenant indicates an expected call of GetTenant.
func (mr *MockObjectHelperMockRecorder) GetTenant(object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTenant", reflect.TypeOf((*MockObjectHelper)(nil).GetTenant), object)
}

// Instance mocks base method.
func (m *MockObjectHelper) Instance() proto.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instance")
	ret0, _ := ret[0].(proto.Message)
	return ret0
}

// Instance indicates an expected call of Instance.
func (mr *MockObjectHelperMockRecorder) Instance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instance", reflect.TypeOf((*MockObjectHelper)(nil).Instance))
}

// IsTenantScoped mocks base method.
func (m *MockObjectHelper) IsTenantScoped() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTenantScoped")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTenantScoped indicates an expected call of IsTenantScoped.
func (mr *MockObjectHelperMockRecorder) IsTenantScoped() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTenantScoped", reflect.TypeOf((*MockObjectHelper)(nil).IsTenantScoped))
}

// List mocks base method.
func (m *MockObjectHelper) List(ctx context.Context, options ListOptions) (ListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, options)
	ret0, _ := ret[0].(ListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockObjectHelperMockRecorder) List(ctx, options any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockObjectHelper)(nil).List), ctx, options)
}

// Plural mocks base method.
func (m *MockObjectHelper) Plural() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Plural")
	ret0, _ := ret[0].(string)
	return ret0
}

// Plural indicates an expected call of Plural.
func (mr *MockObjectHelperMockRecorder) Plural() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Plural", reflect.TypeOf((*MockObjectHelper)(nil).Plural))
}

// SetTenant mocks base method.
func (m *MockObjectHelper) SetTenant(object proto.Message, tenant string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTenant", object, tenant)
}

// SetTenant indicates an expected call of SetTenant.
func (mr *MockObjectHelperMockRecorder) SetTenant(object, tenant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTenant", reflect.TypeOf((*MockObjectHelper)(nil).SetTenant), object, tenant)
}

// Singular mocks base method.
func (m *MockObjectHelper) Singular() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Singular")
	ret0, _ := ret[0].(string)
	return ret0
}

// Singular indicates an expected call of Singular.
func (mr *MockObjectHelperMockRecorder) Singular() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Singular", reflect.TypeOf((*MockObjectHelper)(nil).Singular))
}

// String mocks base method.
func (m *MockObjectHelper) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockObjectHelperMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockObjectHelper)(nil).String))
}

// Update mocks base method.
func (m *MockObjectHelper) Update(ctx context.Context, object proto.Message) (proto.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, object)
	ret0, _ := ret[0].(proto.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockObjectHelperMockRecorder) Update(ctx, object any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockObjectHelper)(nil).Update), ctx, object)
}
