- name: Get AddOnOperator page
  ansible.builtin.uri:
    url: "{{ publish_templates_addon_operator_api_endpoint }}?filter={{ addon_operator_filter | urlencode }}&limit=100&offset={{ addon_operator_page_offset }}"
    validate_certs: "{{ publish_templates_validate_certs | default(true) | bool }}"
    headers:
      authorization: Bearer {{ osac_fulfillment_service_token }}
    status_code: [200, 404, 503]
  register: addon_operator_page
  no_log: true
