ARG TOPOLVM_VERSION=0.41.1

FROM ghcr.io/topolvm/topolvm:${TOPOLVM_VERSION}@sha256:47a2ffbbef09f014aa4c06a143fffa94c5dbf76647c19d8f9fe30bdb5f7f5634 AS topolvm

FROM ubuntu:22.04@sha256:5ec03bb3441e8b0bf3b4f9cd4629a1ae763010dc3035bb8da3ae6cf026486401
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install --yes --no-install-recommends lvm2 xfsprogs \
    && mkdir -p /etc/topolvm \
    && rm -rf /var/lib/apt/lists/*
COPY --from=topolvm /hypertopolvm /usr/local/bin/hypertopolvm
RUN ln -s /usr/local/bin/hypertopolvm /usr/local/bin/lvmd
