// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/volumes_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/volumes_service_grpc.pb.go -destination=volumes_client_mock.go -package=volume VolumesClient
//

// Package volume is a generated GoMock package.
package volume

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockVolumesClient is a mock of VolumesClient interface.
type MockVolumesClient struct {
	ctrl     *gomock.Controller
	recorder *MockVolumesClientMockRecorder
	isgomock struct{}
}

// MockVolumesClientMockRecorder is the mock recorder for MockVolumesClient.
type MockVolumesClientMockRecorder struct {
	mock *MockVolumesClient
}

// NewMockVolumesClient creates a new mock instance.
func NewMockVolumesClient(ctrl *gomock.Controller) *MockVolumesClient {
	mock := &MockVolumesClient{ctrl: ctrl}
	mock.recorder = &MockVolumesClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumesClient) EXPECT() *MockVolumesClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVolumesClient) Create(ctx context.Context, in *privatev1.VolumesCreateRequest, opts ...grpc.CallOption) (*privatev1.VolumesCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVolumesClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVolumesClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockVolumesClient) Delete(ctx context.Context, in *privatev1.VolumesDeleteRequest, opts ...grpc.CallOption) (*privatev1.VolumesDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVolumesClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVolumesClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockVolumesClient) Get(ctx context.Context, in *privatev1.VolumesGetRequest, opts ...grpc.CallOption) (*privatev1.VolumesGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVolumesClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVolumesClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockVolumesClient) List(ctx context.Context, in *privatev1.VolumesListRequest, opts ...grpc.CallOption) (*privatev1.VolumesListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVolumesClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVolumesClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockVolumesClient) Signal(ctx context.Context, in *privatev1.VolumesSignalRequest, opts ...grpc.CallOption) (*privatev1.VolumesSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockVolumesClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockVolumesClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockVolumesClient) Update(ctx context.Context, in *privatev1.VolumesUpdateRequest, opts ...grpc.CallOption) (*privatev1.VolumesUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.VolumesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVolumesClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVolumesClient)(nil).Update), varargs...)
}

// MockVolumesServer is a mock of VolumesServer interface.
type MockVolumesServer struct {
	ctrl     *gomock.Controller
	recorder *MockVolumesServerMockRecorder
	isgomock struct{}
}

// MockVolumesServerMockRecorder is the mock recorder for MockVolumesServer.
type MockVolumesServerMockRecorder struct {
	mock *MockVolumesServer
}

// NewMockVolumesServer creates a new mock instance.
func NewMockVolumesServer(ctrl *gomock.Controller) *MockVolumesServer {
	mock := &MockVolumesServer{ctrl: ctrl}
	mock.recorder = &MockVolumesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVolumesServer) EXPECT() *MockVolumesServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVolumesServer) Create(arg0 context.Context, arg1 *privatev1.VolumesCreateRequest) (*privatev1.VolumesCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVolumesServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVolumesServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockVolumesServer) Delete(arg0 context.Context, arg1 *privatev1.VolumesDeleteRequest) (*privatev1.VolumesDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVolumesServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVolumesServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockVolumesServer) Get(arg0 context.Context, arg1 *privatev1.VolumesGetRequest) (*privatev1.VolumesGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVolumesServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVolumesServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockVolumesServer) List(arg0 context.Context, arg1 *privatev1.VolumesListRequest) (*privatev1.VolumesListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVolumesServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVolumesServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockVolumesServer) Signal(arg0 context.Context, arg1 *privatev1.VolumesSignalRequest) (*privatev1.VolumesSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockVolumesServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockVolumesServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockVolumesServer) Update(arg0 context.Context, arg1 *privatev1.VolumesUpdateRequest) (*privatev1.VolumesUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.VolumesUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVolumesServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVolumesServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedVolumesServer mocks base method.
func (m *MockVolumesServer) mustEmbedUnimplementedVolumesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVolumesServer")
}

// mustEmbedUnimplementedVolumesServer indicates an expected call of mustEmbedUnimplementedVolumesServer.
func (mr *MockVolumesServerMockRecorder) mustEmbedUnimplementedVolumesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVolumesServer", reflect.TypeOf((*MockVolumesServer)(nil).mustEmbedUnimplementedVolumesServer))
}

// MockUnsafeVolumesServer is a mock of UnsafeVolumesServer interface.
type MockUnsafeVolumesServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeVolumesServerMockRecorder
	isgomock struct{}
}

// MockUnsafeVolumesServerMockRecorder is the mock recorder for MockUnsafeVolumesServer.
type MockUnsafeVolumesServerMockRecorder struct {
	mock *MockUnsafeVolumesServer
}

// NewMockUnsafeVolumesServer creates a new mock instance.
func NewMockUnsafeVolumesServer(ctrl *gomock.Controller) *MockUnsafeVolumesServer {
	mock := &MockUnsafeVolumesServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeVolumesServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeVolumesServer) EXPECT() *MockUnsafeVolumesServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedVolumesServer mocks base method.
func (m *MockUnsafeVolumesServer) mustEmbedUnimplementedVolumesServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedVolumesServer")
}

// mustEmbedUnimplementedVolumesServer indicates an expected call of mustEmbedUnimplementedVolumesServer.
func (mr *MockUnsafeVolumesServerMockRecorder) mustEmbedUnimplementedVolumesServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedVolumesServer", reflect.TypeOf((*MockUnsafeVolumesServer)(nil).mustEmbedUnimplementedVolumesServer))
}
