{{- if .Values.enabled }}
apiVersion: kafka.strimzi.io/v1
kind: KafkaUser
metadata:
  name: osac-metering-cost-management-adapter
  namespace: {{ include "cost-management-adapter.kafkaClusterNamespace" . }}
  labels:
    strimzi.io/cluster: {{ include "cost-management-adapter.kafkaClusterName" . }}
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: osac.metering.
          patternType: prefix
        operations:
          - Read
          - Describe
        host: "*"
      - resource:
          type: topic
          name: osac.metering.dlq
          patternType: literal
        operations:
          - Write
        host: "*"
      - resource:
          type: cluster
          name: kafka-cluster
          patternType: literal
        operations:
          - IdempotentWrite
        host: "*"
      - resource:
          type: group
          name: {{ .Values.costManagement.consumerGroup }}
          patternType: literal
        operations:
          - Read
        host: "*"
{{- end }}
