{{- if .Values.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cost-management-adapter.fullname" . }}-read-kafka-secrets
  namespace: {{ include "cost-management-adapter.kafkaClusterNamespace" . }}
  labels:
    {{- include "cost-management-adapter.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - osac-metering-cost-management-adapter
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "cost-management-adapter.fullname" . }}-read-kafka-secrets
  namespace: {{ include "cost-management-adapter.kafkaClusterNamespace" . }}
  labels:
    {{- include "cost-management-adapter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "cost-management-adapter.fullname" . }}-read-kafka-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "cost-management-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
