// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/clusters_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/clusters_service_grpc.pb.go -destination=clusters_client_mock.go -package=cluster ClustersClient
//

// Package cluster is a generated GoMock package.
package cluster

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockClustersClient is a mock of ClustersClient interface.
type MockClustersClient struct {
	ctrl     *gomock.Controller
	recorder *MockClustersClientMockRecorder
	isgomock struct{}
}

// MockClustersClientMockRecorder is the mock recorder for MockClustersClient.
type MockClustersClientMockRecorder struct {
	mock *MockClustersClient
}

// NewMockClustersClient creates a new mock instance.
func NewMockClustersClient(ctrl *gomock.Controller) *MockClustersClient {
	mock := &MockClustersClient{ctrl: ctrl}
	mock.recorder = &MockClustersClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClustersClient) EXPECT() *MockClustersClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClustersClient) Create(ctx context.Context, in *privatev1.ClustersCreateRequest, opts ...grpc.CallOption) (*privatev1.ClustersCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClustersClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClustersClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockClustersClient) Delete(ctx context.Context, in *privatev1.ClustersDeleteRequest, opts ...grpc.CallOption) (*privatev1.ClustersDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClustersClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClustersClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockClustersClient) Get(ctx context.Context, in *privatev1.ClustersGetRequest, opts ...grpc.CallOption) (*privatev1.ClustersGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClustersClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClustersClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockClustersClient) List(ctx context.Context, in *privatev1.ClustersListRequest, opts ...grpc.CallOption) (*privatev1.ClustersListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClustersClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClustersClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockClustersClient) Signal(ctx context.Context, in *privatev1.ClustersSignalRequest, opts ...grpc.CallOption) (*privatev1.ClustersSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockClustersClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockClustersClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockClustersClient) Update(ctx context.Context, in *privatev1.ClustersUpdateRequest, opts ...grpc.CallOption) (*privatev1.ClustersUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ClustersUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClustersClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClustersClient)(nil).Update), varargs...)
}

// MockClustersServer is a mock of ClustersServer interface.
type MockClustersServer struct {
	ctrl     *gomock.Controller
	recorder *MockClustersServerMockRecorder
	isgomock struct{}
}

// MockClustersServerMockRecorder is the mock recorder for MockClustersServer.
type MockClustersServerMockRecorder struct {
	mock *MockClustersServer
}

// NewMockClustersServer creates a new mock instance.
func NewMockClustersServer(ctrl *gomock.Controller) *MockClustersServer {
	mock := &MockClustersServer{ctrl: ctrl}
	mock.recorder = &MockClustersServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClustersServer) EXPECT() *MockClustersServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClustersServer) Create(arg0 context.Context, arg1 *privatev1.ClustersCreateRequest) (*privatev1.ClustersCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClustersServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClustersServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockClustersServer) Delete(arg0 context.Context, arg1 *privatev1.ClustersDeleteRequest) (*privatev1.ClustersDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClustersServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClustersServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockClustersServer) Get(arg0 context.Context, arg1 *privatev1.ClustersGetRequest) (*privatev1.ClustersGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClustersServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClustersServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockClustersServer) List(arg0 context.Context, arg1 *privatev1.ClustersListRequest) (*privatev1.ClustersListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClustersServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClustersServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockClustersServer) Signal(arg0 context.Context, arg1 *privatev1.ClustersSignalRequest) (*privatev1.ClustersSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockClustersServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockClustersServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockClustersServer) Update(arg0 context.Context, arg1 *privatev1.ClustersUpdateRequest) (*privatev1.ClustersUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClustersUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClustersServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClustersServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedClustersServer mocks base method.
func (m *MockClustersServer) mustEmbedUnimplementedClustersServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedClustersServer")
}

// mustEmbedUnimplementedClustersServer indicates an expected call of mustEmbedUnimplementedClustersServer.
func (mr *MockClustersServerMockRecorder) mustEmbedUnimplementedClustersServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedClustersServer", reflect.TypeOf((*MockClustersServer)(nil).mustEmbedUnimplementedClustersServer))
}

// MockUnsafeClustersServer is a mock of UnsafeClustersServer interface.
type MockUnsafeClustersServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeClustersServerMockRecorder
	isgomock struct{}
}

// MockUnsafeClustersServerMockRecorder is the mock recorder for MockUnsafeClustersServer.
type MockUnsafeClustersServerMockRecorder struct {
	mock *MockUnsafeClustersServer
}

// NewMockUnsafeClustersServer creates a new mock instance.
func NewMockUnsafeClustersServer(ctrl *gomock.Controller) *MockUnsafeClustersServer {
	mock := &MockUnsafeClustersServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeClustersServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeClustersServer) EXPECT() *MockUnsafeClustersServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedClustersServer mocks base method.
func (m *MockUnsafeClustersServer) mustEmbedUnimplementedClustersServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedClustersServer")
}

// mustEmbedUnimplementedClustersServer indicates an expected call of mustEmbedUnimplementedClustersServer.
func (mr *MockUnsafeClustersServerMockRecorder) mustEmbedUnimplementedClustersServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedClustersServer", reflect.TypeOf((*MockUnsafeClustersServer)(nil).mustEmbedUnimplementedClustersServer))
}
