// Code generated by MockGen. DO NOT EDIT.
// Source: ../../api/osac/private/v1/cluster_versions_service_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=../../api/osac/private/v1/cluster_versions_service_grpc.pb.go -destination=cluster_versions_client_mock.go -package=cluster ClusterVersionsClient
//

// Package cluster is a generated GoMock package.
package cluster

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/fulfillment-service/internal/api/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockClusterVersionsClient is a mock of ClusterVersionsClient interface.
type MockClusterVersionsClient struct {
	ctrl     *gomock.Controller
	recorder *MockClusterVersionsClientMockRecorder
	isgomock struct{}
}

// MockClusterVersionsClientMockRecorder is the mock recorder for MockClusterVersionsClient.
type MockClusterVersionsClientMockRecorder struct {
	mock *MockClusterVersionsClient
}

// NewMockClusterVersionsClient creates a new mock instance.
func NewMockClusterVersionsClient(ctrl *gomock.Controller) *MockClusterVersionsClient {
	mock := &MockClusterVersionsClient{ctrl: ctrl}
	mock.recorder = &MockClusterVersionsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterVersionsClient) EXPECT() *MockClusterVersionsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClusterVersionsClient) Create(ctx context.Context, in *privatev1.ClusterVersionsCreateRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClusterVersionsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClusterVersionsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockClusterVersionsClient) Delete(ctx context.Context, in *privatev1.ClusterVersionsDeleteRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterVersionsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterVersionsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockClusterVersionsClient) Get(ctx context.Context, in *privatev1.ClusterVersionsGetRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterVersionsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterVersionsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockClusterVersionsClient) List(ctx context.Context, in *privatev1.ClusterVersionsListRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterVersionsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterVersionsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockClusterVersionsClient) Signal(ctx context.Context, in *privatev1.ClusterVersionsSignalRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockClusterVersionsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockClusterVersionsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockClusterVersionsClient) Update(ctx context.Context, in *privatev1.ClusterVersionsUpdateRequest, opts ...grpc.CallOption) (*privatev1.ClusterVersionsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterVersionsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterVersionsClient)(nil).Update), varargs...)
}

// MockClusterVersionsServer is a mock of ClusterVersionsServer interface.
type MockClusterVersionsServer struct {
	ctrl     *gomock.Controller
	recorder *MockClusterVersionsServerMockRecorder
	isgomock struct{}
}

// MockClusterVersionsServerMockRecorder is the mock recorder for MockClusterVersionsServer.
type MockClusterVersionsServerMockRecorder struct {
	mock *MockClusterVersionsServer
}

// NewMockClusterVersionsServer creates a new mock instance.
func NewMockClusterVersionsServer(ctrl *gomock.Controller) *MockClusterVersionsServer {
	mock := &MockClusterVersionsServer{ctrl: ctrl}
	mock.recorder = &MockClusterVersionsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterVersionsServer) EXPECT() *MockClusterVersionsServerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockClusterVersionsServer) Create(arg0 context.Context, arg1 *privatev1.ClusterVersionsCreateRequest) (*privatev1.ClusterVersionsCreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockClusterVersionsServerMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockClusterVersionsServer)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockClusterVersionsServer) Delete(arg0 context.Context, arg1 *privatev1.ClusterVersionsDeleteRequest) (*privatev1.ClusterVersionsDeleteResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockClusterVersionsServerMockRecorder) Delete(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClusterVersionsServer)(nil).Delete), arg0, arg1)
}

// Get mocks base method.
func (m *MockClusterVersionsServer) Get(arg0 context.Context, arg1 *privatev1.ClusterVersionsGetRequest) (*privatev1.ClusterVersionsGetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockClusterVersionsServerMockRecorder) Get(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClusterVersionsServer)(nil).Get), arg0, arg1)
}

// List mocks base method.
func (m *MockClusterVersionsServer) List(arg0 context.Context, arg1 *privatev1.ClusterVersionsListRequest) (*privatev1.ClusterVersionsListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockClusterVersionsServerMockRecorder) List(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockClusterVersionsServer)(nil).List), arg0, arg1)
}

// Signal mocks base method.
func (m *MockClusterVersionsServer) Signal(arg0 context.Context, arg1 *privatev1.ClusterVersionsSignalRequest) (*privatev1.ClusterVersionsSignalResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockClusterVersionsServerMockRecorder) Signal(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockClusterVersionsServer)(nil).Signal), arg0, arg1)
}

// Update mocks base method.
func (m *MockClusterVersionsServer) Update(arg0 context.Context, arg1 *privatev1.ClusterVersionsUpdateRequest) (*privatev1.ClusterVersionsUpdateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*privatev1.ClusterVersionsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockClusterVersionsServerMockRecorder) Update(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClusterVersionsServer)(nil).Update), arg0, arg1)
}

// mustEmbedUnimplementedClusterVersionsServer mocks base method.
func (m *MockClusterVersionsServer) mustEmbedUnimplementedClusterVersionsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedClusterVersionsServer")
}

// mustEmbedUnimplementedClusterVersionsServer indicates an expected call of mustEmbedUnimplementedClusterVersionsServer.
func (mr *MockClusterVersionsServerMockRecorder) mustEmbedUnimplementedClusterVersionsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedClusterVersionsServer", reflect.TypeOf((*MockClusterVersionsServer)(nil).mustEmbedUnimplementedClusterVersionsServer))
}

// MockUnsafeClusterVersionsServer is a mock of UnsafeClusterVersionsServer interface.
type MockUnsafeClusterVersionsServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeClusterVersionsServerMockRecorder
	isgomock struct{}
}

// MockUnsafeClusterVersionsServerMockRecorder is the mock recorder for MockUnsafeClusterVersionsServer.
type MockUnsafeClusterVersionsServerMockRecorder struct {
	mock *MockUnsafeClusterVersionsServer
}

// NewMockUnsafeClusterVersionsServer creates a new mock instance.
func NewMockUnsafeClusterVersionsServer(ctrl *gomock.Controller) *MockUnsafeClusterVersionsServer {
	mock := &MockUnsafeClusterVersionsServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeClusterVersionsServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeClusterVersionsServer) EXPECT() *MockUnsafeClusterVersionsServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedClusterVersionsServer mocks base method.
func (m *MockUnsafeClusterVersionsServer) mustEmbedUnimplementedClusterVersionsServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedClusterVersionsServer")
}

// mustEmbedUnimplementedClusterVersionsServer indicates an expected call of mustEmbedUnimplementedClusterVersionsServer.
func (mr *MockUnsafeClusterVersionsServerMockRecorder) mustEmbedUnimplementedClusterVersionsServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedClusterVersionsServer", reflect.TypeOf((*MockUnsafeClusterVersionsServer)(nil).mustEmbedUnimplementedClusterVersionsServer))
}
