version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  settings:
    goconst:
      ignore-tests: true
    revive:
      rules:
        - name: comment-spacings
    staticcheck:
      checks:
        - all
        - "-QF1008"
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - lll
        path: pkg/
      - linters:
          - errcheck
        path: ".*_test.go$"
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
