apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.19-nightly.20261006.c8d0d88.120.1
appVersion: 0.0.19-nightly.20261006.c8d0d88.120.1
