apiVersion: v2
name: osac-operator
description: OSAC Operator - manages OSAC custom resources
type: application
version: 0.0.12-nightly.20260903.e6e4f62.67.1
appVersion: 0.0.12-nightly.20260903.e6e4f62.67.1
