// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/osac-project/osac/proto/gen/osac/private/v1 (interfaces: FabricDomainsClient,VirtualNetworksClient)
//
// Generated by this command:
//
//	mockgen -destination=clients_mock.go -package=fabricdomain github.com/osac-project/osac/proto/gen/osac/private/v1 FabricDomainsClient,VirtualNetworksClient
//

// Package fabricdomain is a generated GoMock package.
package fabricdomain

import (
	context "context"
	reflect "reflect"

	privatev1 "github.com/osac-project/osac/proto/gen/osac/private/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockFabricDomainsClient is a mock of FabricDomainsClient interface.
type MockFabricDomainsClient struct {
	ctrl     *gomock.Controller
	recorder *MockFabricDomainsClientMockRecorder
	isgomock struct{}
}

// MockFabricDomainsClientMockRecorder is the mock recorder for MockFabricDomainsClient.
type MockFabricDomainsClientMockRecorder struct {
	mock *MockFabricDomainsClient
}

// NewMockFabricDomainsClient creates a new mock instance.
func NewMockFabricDomainsClient(ctrl *gomock.Controller) *MockFabricDomainsClient {
	mock := &MockFabricDomainsClient{ctrl: ctrl}
	mock.recorder = &MockFabricDomainsClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFabricDomainsClient) EXPECT() *MockFabricDomainsClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFabricDomainsClient) Create(ctx context.Context, in *privatev1.FabricDomainsCreateRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockFabricDomainsClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFabricDomainsClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockFabricDomainsClient) Delete(ctx context.Context, in *privatev1.FabricDomainsDeleteRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockFabricDomainsClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFabricDomainsClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockFabricDomainsClient) Get(ctx context.Context, in *privatev1.FabricDomainsGetRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockFabricDomainsClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockFabricDomainsClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockFabricDomainsClient) List(ctx context.Context, in *privatev1.FabricDomainsListRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockFabricDomainsClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockFabricDomainsClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockFabricDomainsClient) Signal(ctx context.Context, in *privatev1.FabricDomainsSignalRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockFabricDomainsClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockFabricDomainsClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockFabricDomainsClient) Update(ctx context.Context, in *privatev1.FabricDomainsUpdateRequest, opts ...grpc.CallOption) (*privatev1.FabricDomainsUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.FabricDomainsUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockFabricDomainsClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockFabricDomainsClient)(nil).Update), varargs...)
}

// MockVirtualNetworksClient is a mock of VirtualNetworksClient interface.
type MockVirtualNetworksClient struct {
	ctrl     *gomock.Controller
	recorder *MockVirtualNetworksClientMockRecorder
	isgomock struct{}
}

// MockVirtualNetworksClientMockRecorder is the mock recorder for MockVirtualNetworksClient.
type MockVirtualNetworksClientMockRecorder struct {
	mock *MockVirtualNetworksClient
}

// NewMockVirtualNetworksClient creates a new mock instance.
func NewMockVirtualNetworksClient(ctrl *gomock.Controller) *MockVirtualNetworksClient {
	mock := &MockVirtualNetworksClient{ctrl: ctrl}
	mock.recorder = &MockVirtualNetworksClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVirtualNetworksClient) EXPECT() *MockVirtualNetworksClientMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVirtualNetworksClient) Create(ctx context.Context, in *privatev1.VirtualNetworksCreateRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksCreateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Create", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksCreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockVirtualNetworksClientMockRecorder) Create(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Create), varargs...)
}

// Delete mocks base method.
func (m *MockVirtualNetworksClient) Delete(ctx context.Context, in *privatev1.VirtualNetworksDeleteRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksDeleteResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Delete", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksDeleteResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockVirtualNetworksClientMockRecorder) Delete(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Delete), varargs...)
}

// Get mocks base method.
func (m *MockVirtualNetworksClient) Get(ctx context.Context, in *privatev1.VirtualNetworksGetRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksGetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksGetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockVirtualNetworksClientMockRecorder) Get(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Get), varargs...)
}

// List mocks base method.
func (m *MockVirtualNetworksClient) List(ctx context.Context, in *privatev1.VirtualNetworksListRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksListResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "List", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockVirtualNetworksClientMockRecorder) List(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockVirtualNetworksClient)(nil).List), varargs...)
}

// Signal mocks base method.
func (m *MockVirtualNetworksClient) Signal(ctx context.Context, in *privatev1.VirtualNetworksSignalRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksSignalResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Signal", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksSignalResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Signal indicates an expected call of Signal.
func (mr *MockVirtualNetworksClientMockRecorder) Signal(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Signal), varargs...)
}

// Update mocks base method.
func (m *MockVirtualNetworksClient) Update(ctx context.Context, in *privatev1.VirtualNetworksUpdateRequest, opts ...grpc.CallOption) (*privatev1.VirtualNetworksUpdateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Update", varargs...)
	ret0, _ := ret[0].(*privatev1.VirtualNetworksUpdateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockVirtualNetworksClientMockRecorder) Update(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVirtualNetworksClient)(nil).Update), varargs...)
}
