{{- if .Values.sharedPostgres.enabled }}
{{- $prefix := include "osac-workload.dbPrefix" . }}
{{- $pgHost := printf "postgres.%s.svc.cluster.local" .Values.baseNamespace }}
apiVersion: v1
kind: Secret
metadata:
  name: fulfillment-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgres://{{ $prefix }}_service@{{ $pgHost }}:5432/{{ $prefix }}_service?sslmode=verify-full&sslrootcert=/etc/fulfillment-grpc-server/db/sslrootcert&sslcert=/etc/fulfillment-grpc-server/db/sslcert&sslkey=/etc/fulfillment-grpc-server/db/sslkey"
---
apiVersion: v1
kind: Secret
metadata:
  name: metering-db
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: "postgres://{{ $prefix }}_metering@{{ $pgHost }}:5432/{{ $prefix }}_metering?sslmode=verify-full&sslrootcert=/etc/metering/db/sslrootcert&sslcert=/etc/metering/db/sslcert&sslkey=/etc/metering/db/sslkey"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.service.certs.issuerRef.kind }}
    name: {{ .Values.service.certs.issuerRef.name }}
  commonName: "{{ $prefix }}_service"
  usages:
  - client auth
  secretName: postgres-client-cert-service
  privateKey:
    rotationPolicy: Always
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: postgres-client-metering
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "osac-workload.labels" . | nindent 4 }}
spec:
  issuerRef:
    kind: {{ .Values.service.certs.issuerRef.kind }}
    name: {{ .Values.service.certs.issuerRef.name }}
  commonName: "{{ $prefix }}_metering"
  usages:
  - client auth
  secretName: postgres-client-cert-metering
  privateKey:
    rotationPolicy: Always
{{- end }}
